### ISSUE TITLE
Title: Add refresh button in Joke Extension.

### ISSUE THREAD

**Issue by Khushbu-kumari-87090** [ridsuteri/Awesome-Chrome-Extensions#100]
### Is your feature request related to a problem? Please describe.

Each time, when user wants a new joke, he or she has to open the extension again and again.

### Describe the solution you'd like.

I have added a refresh button, so that we can get new jokes just by clicking at the refresh button.

### Describe alternatives you've considered.

We can add download button in future, so that if user likes a jokes, he or she can keep it.
We can also add a share option so that user can share it with his or her friends via social media.

**Comment by ridsuteri** [comment]
since the PR is merged, I am closing this issue :)
