### ISSUE TITLE
Title: Currency Converter Extension 

### ISSUE THREAD

**Issue by AkankshaGawade** [ridsuteri/Awesome-Chrome-Extensions#109]
It will be an awesome extension which converts the respective currency let's say USD into desired one that's gonna be INR. Please assign this to me under GSSOC'22.

**Comment by ridsuteri** [comment]
@AkankshaGawade a similar extension already exists in the repository, so I can't assign the exactly duplicate issue to you again :(( but do let me know if you want to modify the existing one...
