### ISSUE TITLE
want to add fresh quotes extension

### ISSUE THREAD

**Issue by adi2002vicky** [ridsuteri/Awesome-Chrome-Extensions#11]
this extension give you a fresh quotes
i make pull request pls review it mam

**Comment by Atharv-110** [comment]
Hey please assign this issue to me as I have a great knowledge of styling so I will be obliged to represent the best extension for this.

**Comment by ridsuteri** [comment]
I am assigning the issue to @adi2002vicky since he has posted the issues first. @Atharv-110 sure you can take up the modification after @adi2002vicky submit a pr or you can add another issue

**Comment by vaibhavmehro** [comment]
@ridsuteri i got that thanks

**Comment by ridsuteri** [comment]
@adi2002vicky are you working on this? or should I assign it to someone else?

**Comment by vaibhavmehro** [comment]
I can work on it if you allow me @ridsuteri

**Comment by adi2002vicky** [comment]
pls check pr sir @ridsuteri

**Comment by ridsuteri** [comment]
> pls check pr sir @ridsuteri

since your last PR was plagiarised, I am assigning this issue to @Atharv-110 now

**Comment by ridsuteri** [comment]
any updates @Atharv-110 ?

**Comment by Atharv-110** [comment]
Yes @ridsuteri I need few days like 3 to 4 as my mid semester examinations are going on.

**Comment by ridsuteri** [comment]
@Atharv-110 working on it or should i close this issue?

**Comment by Atharv-110** [comment]
@ridsuteri till when do you expect me to do this as i am stuck in some urgent work for this week?

**Comment by ridsuteri** [comment]
> @ridsuteri till when do you expect me to do this as i am stuck in some urgent work for this week?

Umm the earlier the better, maybe submit it after this week!

**Comment by Sukriti-m** [comment]
> > @ridsuteri till when do you expect me to do this as i am stuck in some urgent work for this week?
> 
> Umm the earlier the better, maybe submit it after this week!

@ridsuteri  If this task is being delayed, then I'd be glad to work on it. I am a GSSoC'22 contributor.

**Comment by ridsuteri** [comment]
go ahead @Sukriti-m !
