### ISSUE TITLE
Title: GRE Vocab

### ISSUE THREAD

**Issue by RiyaBhandari-2811** [ridsuteri/Awesome-Chrome-Extensions#113]
### Is your feature request related to a problem? Please describe.

As we all know GRE Verbal section is very tough and learning vocab that to in these busyy days is very tough . what if we don't need to manually search for each gre words find their definition and then learn .. sounds pretty exhausting 😥😶  right ?

### Describe the solution you'd like.

So this is where `GRE Vocab` comes in . 
 These Extension help the GRE aspirants get all vocab   `Word + Definition`   at one place and that too in one click , sounds cool 😎right .

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

I just have idea . If you @ridsuteri  assign these issue to me i'll immediately start working on it .

**Comment by ridsuteri** [comment]
Sounds very useful, go ahead @RiyaBhandari-2811 :)

**Comment by RiyaBhandari-2811** [comment]
@ridsuteri  can you pls close these issue
