### ISSUE TITLE
The Github Extension

### ISSUE THREAD

**Issue by shreya024** [ridsuteri/Awesome-Chrome-Extensions#124]
### Is your feature request related to a problem? Please describe.

I would like to add a Github Extension

### Describe the solution you'd like.

This Extension will showcase the status of feed, issues and recent activity of a Github User.
* [x]  GSSoC  Contributor

 Kindly assign it to me. @ridsuteri

### Describe alternatives you've considered.

I'm a GSSoC contributor and would like to take up this issue.

### Add any other context or screenshots about the feature request here.

I will use the Github REST API for this extension.

**Comment by ridsuteri** [comment]
sounds fun @shreya024, go ahead I am assigning you the issue!
