### ISSUE TITLE
want to add some new quotes extension

### ISSUE THREAD

**Issue by Khushbu-kumari-87090** [ridsuteri/Awesome-Chrome-Extensions#13]
hello@ridsuteri  i really want to work your cool project Awesome -chrome-Extension so please assign me.
i am gssoc contributor. and its my first time to open source please assign me.please!

**Comment by ridsuteri** [comment]
@Khushbu-kumari-87090 a similar issue is already assigned, is your issue different from #12 issues?
If yes then please specify, else I can't assign the duplicate issue :(

**Comment by priyanshi1282** [comment]
hey @ridsuteri , I'm also willing to add a random quotes generator extension. As it will generate some motivational quotes, it will help people to clear their mind and focus again on their work.
If this issue is not assigned to anyone, Please assign me under GSSoC'22 Contribution.

**Comment by ridsuteri** [comment]
since a similar issue #11  is already open, I am closing this one :((
