### ISSUE TITLE
Want to add BMI CALCULATER Extensions

### ISSUE THREAD

**Issue by adi2002vicky** [ridsuteri/Awesome-Chrome-Extensions#14]
this extension help to calculate body mass index
pls check pr mam

**Comment by sarthakk24** [comment]
Can i work on this issue under gssoc 2022

**Comment by kalash2205** [comment]
hi @ridsuteri 
can i work on this issue

kalash singhal
gssoc contributor

**Comment by sudip004** [comment]
hi sir i am sudip basak ..i am work this issue

**Comment by ridsuteri** [comment]
@sarthakk24 @kalash2205 @sudip004 the issues are assigned on first come first served basis, hence I am assigning the issue to @adi2002vicky . If he fails to submit a Pr It will be assigned to the person after him in the queue :)

**Comment by adi2002vicky** [comment]
@ridsuteri  please check Pr mam/sir i have done this work..

**Comment by ridsuteri** [comment]
@adi2002vicky We will start reviewing and merging PRs in 1-2 days after proper orientation of mentors, Don't worry about that. Keep contributing :)

**Comment by adi2002vicky** [comment]
okk thankyou mam

**Comment by ridsuteri** [comment]
closing this issue since the PR is merged
