### ISSUE TITLE
COVID-19 Live Statistics Chrome Extension

### ISSUE THREAD

**Issue by abhilipsasahoo03** [ridsuteri/Awesome-Chrome-Extensions#141]
### Is your feature request related to a problem? Please describe.

Sometimes, it's confusing as to how and from which resource we could find accurate COVID-19 statistics. 

### Describe the solution you'd like.

A chrome extension which can give live statistics of affected countries, daily cases, recovery rate and related graphs. 

### Describe alternatives you've considered.

None

### Add any other context or screenshots about the feature request here.

![148749420-879eaba5-28f9-460d-be74-f0d288e18850](https://user-images.githubusercontent.com/80174214/160664069-a31d3ebd-4561-4333-8258-355ff317ad97.png)
![148749380-0fd2dac2-4f21-4758-91fd-739ff409362c](https://user-images.githubusercontent.com/80174214/160664087-5ef46c97-7827-45e4-8652-62f5ee1430a4.png)

**Comment by ridsuteri** [comment]
any updates on this @abhilipsasahoo03 ?

**Comment by abhilipsasahoo03** [comment]
> any updates on this @abhilipsasahoo03 ?
Hi @ridsuteri sorry for the delay I'm having end sems this week, but I'll be making a PR by tomorrow night. Sorry once again!

**Comment by tasneemahmed123** [comment]
can i work on this issue?

**Comment by ridsuteri** [comment]
@abhilipsasahoo03 are you still working on this or should I assign it to someone else?

**Comment by abhilipsasahoo03** [comment]
> @abhilipsasahoo03 are you still working on this or should I assign it to someone else?

hi @ridsuteri due to some problem I'm unable to complete this extension, so you can assign it to someone else.

**Comment by navyasharma0203** [comment]
I would like to work on this issue. Can you assign this to me?

**Comment by ridsuteri** [comment]
go ahead @navyasharma0203 :)

**Comment by ridsuteri** [comment]
@navyasharma0203 any updates?

**Comment by ridsuteri** [comment]
Please make the PR before 10-11PM today, if you want this contribution to be  counted in GSSoC'22
