### ISSUE TITLE
Title: Want to add a background website changer extension

### ISSUE THREAD

**Issue by iamrahulmahato** [ridsuteri/Awesome-Chrome-Extensions#146]
### Is your feature request related to a problem? Please describe.

In most of the time we don't like background of a website

### Describe the solution you'd like.

It will be a extension which will change the background of a website

### Describe alternatives you've considered.

![before](https://user-images.githubusercontent.com/49890655/161337023-2b7038fd-0eb9-4b81-af19-20a3024c5357.jpg)
![after](https://user-images.githubusercontent.com/49890655/161337037-2826be29-b3e9-4adb-b05a-2677169515cb.jpg)
![before1](https://user-images.githubusercontent.com/49890655/161337048-a7328c50-e728-44ec-b587-e8be162d5fed.jpg)
![after1](https://user-images.githubusercontent.com/49890655/161337058-7ea812db-3d27-491a-8584-7da723723840.jpg)

**Comment by iamrahulmahato** [comment]
I would like to solve the issue
I'm a GSSOC22 contributor

**Comment by ridsuteri** [comment]
@iamrahulmahato the issue already exists :(
