### ISSUE TITLE
Country-Capital Chrome Extension

### ISSUE THREAD

**Issue by Sukriti-m** [ridsuteri/Awesome-Chrome-Extensions#158]
### Is your feature request related to a problem? Please describe.

It's fun to know about capital cities of different countries.

### Describe the solution you'd like.

I will add the extension in which the user will enter the country's name and in response will be shown the name of the capital city.

### Describe alternatives you've considered.

-

### Add any other context or screenshots about the feature request here.

I am contributor at GSSoC '22. Please assign this issue to me.

**Comment by praniti111** [comment]
Go ahead @Sukriti-m
