### ISSUE TITLE
News Extension

### ISSUE THREAD

**Issue by shreya024** [ridsuteri/Awesome-Chrome-Extensions#159]
### Is your feature request related to a problem? Please describe.

I would like to add a News Extension

### Describe the solution you'd like.

This Extension will showcase the top headlines in India.
* [x]  GSSoC  Contributor

 Kindly assign it to me. @ridsuteri

### Describe alternatives you've considered.

I'm a GSSoC contributor and would like to take up this issue. I will be using the News API

### Add any other context or screenshots about the feature request here.

I also have an idea of customizing it ..like the user can give input of the 2-letter ISO 3166-1 code of the country you want to get headlines for. like in for India 
OR 
categories like business/science etc.
Which one should I do? Kindly guide

**Comment by ridsuteri** [comment]
@shreya024 the idea sounds great, I think the category wise section is good for now, maybe you can add the country section later with some other PR

**Comment by shreya024** [comment]
> @shreya024 the idea sounds great, I think the category wise section is good for now, maybe you can add the country section later with some other PR

Okay thank you for your suggestion

**Comment by shreya024** [comment]
> > @shreya024 the idea sounds great, I think the category wise section is good for now, maybe you can add the country section later with some other PR
> 
> Okay thank you for your suggestion



> @shreya024 the idea sounds great, I think the category wise section is good for now, maybe you can add the country section later with some other PR

Should I make another issue for this or just raise another PR with the country section and better styling?

**Comment by ridsuteri** [comment]
Raise another issue and then raise a PR
