### ISSUE TITLE
Code Editor Extension

### ISSUE THREAD

**Issue by Jyo561** [ridsuteri/Awesome-Chrome-Extensions#16]
So it will be an extension which provides a code editor to write code on like chrome extentions work on Chromebooks

**Comment by ridsuteri** [comment]
look great! go ahead @Jyo561

**Comment by Jyo561** [comment]
Can you assign GSSoC22 to it

**Comment by ridsuteri** [comment]
@Jyo561 We will add labels in 1-2 days don't worry about that :)

**Comment by Jyo561** [comment]
Thank you

**Comment by ridsuteri** [comment]
@Jyo561 any update on this?

**Comment by Jyo561** [comment]
yup currently working on its UI

**Comment by ridsuteri** [comment]
status on this @Jyo561 ?

**Comment by Jyo561** [comment]
Yeah I am still working on its UI
had to take a week off due to exams so it will be a little late

**Comment by ridsuteri** [comment]
updates on this @Jyo561 ?
