### ISSUE TITLE
Title: User form taking 

### ISSUE THREAD

**Issue by kalashvasaniya** [ridsuteri/Awesome-Chrome-Extensions#169]
### Is your feature request related to a problem? Please describe.

So, basically this project is very big like I have to give 6-7 days on this!

### Describe the solution you'd like.

If a user fill form and submit  its directly send to the mail of the other user - this project is big because I have to work on frontend as well as backend & also manifest file! 

### Describe alternatives you've considered.

Pls. assign to level 3 :)

**Comment by ridsuteri** [comment]
sounds interesting @kalashvasaniya , go ahead
