### ISSUE TITLE
progress bar extension

### ISSUE THREAD

**Issue by aishalg** [ridsuteri/Awesome-Chrome-Extensions#17]
want to add the progress extention which tell the user how much progress has been made while navigating the website

**Comment by ridsuteri** [comment]
go ahead @aishalg :)

**Comment by aishalg** [comment]
thankyou

**Comment by ridsuteri** [comment]
@aishalg any updates on this?

**Comment by aishalg** [comment]
yes, working on it..will revert back soon @ridsuteri

**Comment by ridsuteri** [comment]
@aishalg updates?
