### ISSUE TITLE
Programmer Jokes Extension

### ISSUE THREAD

**Issue by Sukriti-m** [ridsuteri/Awesome-Chrome-Extensions#172]
### Is your feature request related to a problem? Please describe.

This extension will give a good laugh to the people with it's hilarious Programmer Jokes.

### Describe the solution you'd like.

I will add the extension in which the user will be shown a random programmer joke.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

I am contributor at GSSoC22. Please assign this issue to me.

@ridsuteri @praniti111

**Comment by ridsuteri** [comment]
@Sukriti-m similar project already exists
