### ISSUE TITLE
NotePad Extension

### ISSUE THREAD

**Issue by iamrahulmahato** [ridsuteri/Awesome-Chrome-Extensions#178]
### Is your feature request related to a problem? Please describe.

Most of us while browsing internet when we need to write something so every time we need to open the notepad

### Describe the solution you'd like.

But not anymore we will create a Notepad Extension which will help you in the browser only to write a note

### Describe alternatives you've considered.

![Screenshot 2022-04-12 090338](https://user-images.githubusercontent.com/49890655/163005435-d4abb60f-82c1-478d-ae60-33542a27807b.png)

**Comment by ridsuteri** [comment]
@iamrahulmahato I am expecting that these notes are being saved in local storage and are not just valid for a single session...

**Comment by iamrahulmahato** [comment]
@ridsuteri yes it will store in local storage
