### ISSUE TITLE
Leetcode daily challenge reminder extension

### ISSUE THREAD

**Issue by MurtazaMister** [ridsuteri/Awesome-Chrome-Extensions#18]
Hey @ridsuteri, I am interested in adding an extension to the project "Awesome-Chrome-Extensions" under **Gssoc'22**, that would remind the user to solve daily Leetcode challenges and some other additional features if time permits.

Thank you :)

**Comment by ridsuteri** [comment]
sounds great @MurtazaMister , go ahead I am assigning you the issue :)

**Comment by ridsuteri** [comment]
any progress @MurtazaMister

**Comment by MurtazaMister** [comment]
Leetcode ready, Code Chef and code forces will be ready anytime soon :) @ridsuteri
