### ISSUE TITLE
Link issue section of this repo in readme.md

### ISSUE THREAD

**Issue by aaryahjolia** [ridsuteri/Awesome-Chrome-Extensions#19]
In the screenshot below : 

![GSSoC](https://user-images.githubusercontent.com/82600388/156120976-ca977c9d-ad8f-49ab-a3aa-3bae3c415e44.png)

##
### The 'contributions welcome' image takes us to dwyl/esta github repo. It should take us to this (ridsuteri's) issue section.

I would love to work on this issue.
I'm a GSSoC'22 Contributor.
Please assign this to me.

**Comment by Pranshu321** [comment]
@ridsuteri I would like to work on this, I have understood the **flow of the readme** how it should be presented and assure you that changes will **enhance the reader experience**. \

### Please Assign this issue to me as a GSSOC'22 Contributor.

**Comment by aaryahjolia** [comment]
@Pranshu321  Assigning issues work on first come first serve basis. If I'm unable to do it in a day after assigned, then you will get a chance.

**Comment by ridsuteri** [comment]
Yes @Pranshu321, issues will be assigned on fcfs basis. But don't worry once @aaryahjolia submits his pr, you can open another issues if you feel any need of further enhancement in the readme :)
