### ISSUE TITLE
Background Remover

### ISSUE THREAD

**Issue by shreya024** [ridsuteri/Awesome-Chrome-Extensions#190]
### Is your feature request related to a problem? Please describe.

This extension will remove the background of an uploaded image and return its png with a transparent background.

### Describe the solution you'd like.

I will remove the background using remove.bg api

### Describe alternatives you've considered.

* [x]  GSSoC  Contributor

 Kindly assign it to me. @ridsuteri

### Add any other context or screenshots about the feature request here.

I was thinking about adding a resize option as well. Kindly guide

**Comment by ridsuteri** [comment]
@shreya024 sounds good and maybe you can also add an option for custom backgrounds for the bg removed image.

**Comment by shreya024** [comment]
> @shreya024 sounds good and maybe you can also add an option for custom backgrounds for the bg removed image.

Sure but I will have to find a suitable api for that.Is it okay if I do it in another PR?

**Comment by ridsuteri** [comment]
> > @shreya024 sounds good and maybe you can also add an option for custom backgrounds for the bg removed image.
> 
> Sure but I will have to find a suitable api for that.Is it okay if I do it in another PR?

sure, it was just a suggestion :))
