### ISSUE TITLE
Title: Music Player extension!

### ISSUE THREAD

**Issue by kalashvasaniya** [ridsuteri/Awesome-Chrome-Extensions#194]
### Is your feature request related to a problem? Please describe.

Again big project but not complicated :)

### Describe the solution you'd like.

I want to make a music player in which you can play your own song!
Music play in the background also!

### Describe alternatives you've considered.

I have to work on both Frontend & backend so I need 6-7 Days of time 👍

### Add any other context or screenshots about the feature request here.

Assigne it to lvl-3!

**Comment by ridsuteri** [comment]
> 

sounds fun, but will this extension play local songs or song from the web?

**Comment by kalashvasaniya** [comment]
> sounds fun, but will this extension play local songs or songs from the web?

The song which we put in HTML file, it's like personal music player & yaa I have to make a proper README.md file for how to use & add your own personal music!

**Comment by ridsuteri** [comment]
> > sounds fun, but will this extension play local songs or songs from the web?
> 
> The song which we put in HTML file, it's like personal music player & yaa I have to make a proper README.md file for how to use & add your own personal music!

hmm that will be a bit of hassle, but no issues, go ahead :)
