### ISSUE TITLE
Your Age Extension 

### ISSUE THREAD

**Issue by Mrjoy832** [ridsuteri/Awesome-Chrome-Extensions#196]
### Is your feature request related to a problem? Please describe.

This Extension is used to determine Your age with Your given Date of Birth.
Mainly HTML,CSS,JS will be used to make this awesome extension.

### Describe the solution you'd like.

I will be using HTML, CSS, Js to make this ...here an div section will be given to put Date of birth from user and by that The age of user will be calculated

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.
 please assign , I have to start Working on it.

**Comment by Mrjoy832** [comment]
@kalashvasaniya , please assign on it

**Comment by kalashvasaniya** [comment]
> ### Is your feature request related to a problem? Please describe.
> This Extension is used to determine Your age with Your given Date of Birth. Mainly HTML,CSS,JS will be used to make this awesome extension.
> 
> ### Describe the solution you'd like.
> I will be using HTML, CSS, Js to make this ...here an div section will be given to put Date of birth from user and by that The age of user will be calculated
> 
> ### Describe alternatives you've considered.
> NA
> 
> ### Add any other context or screenshots about the feature request here.
> @kalashvasaniya please assign , I have to start Working on it.

I'm not PA Bro :')

**Comment by Mrjoy832** [comment]
> > ### Is your feature request related to a problem? Please describe.
> > This Extension is used to determine Your age with Your given Date of Birth. Mainly HTML,CSS,JS will be used to make this awesome extension.
> > ### Describe the solution you'd like.
> > I will be using HTML, CSS, Js to make this ...here an div section will be given to put Date of birth from user and by that The age of user will be calculated
> > ### Describe alternatives you've considered.
> > NA
> > ### Add any other context or screenshots about the feature request here.
> > @kalashvasaniya please assign , I have to start Working on it.
> 
> I'm not PA Bro :')

okay Sorry bro

**Comment by praniti111** [comment]
go ahead @Mrjoy832
