### ISSUE TITLE
Want to add programming meme extension

### ISSUE THREAD

**Issue by MeetaHaldar** [ridsuteri/Awesome-Chrome-Extensions#20]
Hello @ridsuteri,
I want to add programming meme extension to this repository.
which will provide you a fresh meme everytime you click the extension button

Thanks and regards,
Meeta Haldar,
A GSSOC 2022 Contributor.

**Comment by ridsuteri** [comment]
sounds great @MeetaHaldar , go ahead I am assigning you the issue :)
