### ISSUE TITLE
Virtual Dice

### ISSUE THREAD

**Issue by SupriyaGembali** [ridsuteri/Awesome-Chrome-Extensions#202]
Hii I'm a GSSoc22 contributor and I'm willing to make a pull request in this repository on my project which is Virtual Dice.

###How does it work
if you use this extension ,it generates a random number between 1 to 6.

please refer to these images
<img width="1245" alt="ss1" src="https://user-images.githubusercontent.com/94470209/164040292-36ce8e5e-756c-4989-ae81-766de970d907.png">
<img width="1245" alt="ss2" src="https://user-images.githubusercontent.com/94470209/164040549-33204be3-692f-441e-8a9e-1da9de29fec1.png">

**Comment by ridsuteri** [comment]
umm @SupriyaGembali, That doesn't seem to be of much use, maybe try coming up with something useful or make this one something more useful :(
