### ISSUE TITLE
Background Remover Extension Enhancement

### ISSUE THREAD

**Issue by shreya024** [ridsuteri/Awesome-Chrome-Extensions#203]
### Is your feature request related to a problem? Please describe.

This enhancement will merge the background and foreground and return the merged image.

### Describe the solution you'd like.

I will merge images using [this api](https://image-merger.herokuapp.com/)

### Describe alternatives you've considered.

* [x]  GSSoC  Contributor

 Kindly assign it to me. @ridsuteri

**Comment by shreya024** [comment]
I'm working on the implemention. But getting this error
```
Access to fetch at 'https://image-merger.herokuapp.com/api/v1.0/merge-images/' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

```
@ridsuteri It would be great if u could provide some resources to help me resolve it.

**Comment by ridsuteri** [comment]
> ge-merger.herokuapp.com/api/v1.0/me

try using allow Cors chrome extension
