### ISSUE TITLE
Trigonometric calculator Extension

### ISSUE THREAD

**Issue by Mrjoy832** [ridsuteri/Awesome-Chrome-Extensions#204]
### Is your feature request related to a problem? Please describe.

Trigonometric calculator Extension is an Extension  which will help to calculate the sin, cos,tan value of any given angle and it will display the relevant result . It's made using HTML,CSS,JS

### Describe the solution you'd like.

It will be made using HTML,CSS,JS ...here user has to put Angle value in Degree format and also user can put input as precision value and the output value of sin ,cos,tan of the input angle will be displayed in different Div Section.

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

KIndly, assign it to me..I have to start working on it.

**Comment by Mrjoy832** [comment]
@praniti111 , please assign it to me.

**Comment by ridsuteri** [comment]
> e using HTML,CSS,JS ...here user has to put Angle value in Degree format and also user can put input as precision value and the output value of sin ,cos,tan of the input angle will be displayed in different Div Section.
> 
> ### Describe alternatives you've considered.

@Mrjoy832 There's already a calculator extension, maybe you can add these features to that extension?

**Comment by Mrjoy832** [comment]
> > e using HTML,CSS,JS ...here user has to put Angle value in Degree format and also user can put input as precision value and the output value of sin ,cos,tan of the input angle will be displayed in different Div Section.
> > 
> > ### Describe alternatives you've considered.
> 
> @Mrjoy832 There's already a calculator extension, maybe you can add these features to that extension?

Okay I will try
