### ISSUE TITLE
Alarm Clock Extension

### ISSUE THREAD

**Issue by Mrjoy832** [ridsuteri/Awesome-Chrome-Extensions#205]
### Is your feature request related to a problem? Please describe.

Alarm Clock is very essential Tool for every Student as well as professional..So I want to add a Alarm Clock Extension in this repo.

### Describe the solution you'd like.

It will be made using HTML,CSS,JS and must be tested by uploading into Chrome Web Store.

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

It's not only set alarm clock it also show time ..so it also works as a digital Clock

**Comment by Mrjoy832** [comment]
@praniti111 @ridsuteri , please assign it to me.

**Comment by ridsuteri** [comment]
> 

will this work in the background, bcz else it would be of not much use?

**Comment by ridsuteri** [comment]
any updates @Mrjoy832 ?
