### ISSUE TITLE
Title: Github profile search

### ISSUE THREAD

**Issue by kalashvasaniya** [ridsuteri/Awesome-Chrome-Extensions#207]
### Is your feature request related to a problem? Please describe.

You can search any user from github by simply write her name in extension :)

### Describe the solution you'd like.

Big project take time made by using HTML, CSS & JavaScript!

### Describe alternatives you've considered.

Try to make better UI also

**Comment by ridsuteri** [comment]
@kalashvasaniya a similar issue is already there that searches your profiles and as well as gives some info about it. maybe you can enhance that?

**Comment by kalashvasaniya** [comment]
> @kalashvasaniya a similar issue is already there that searches your profiles and as well as gives some info about it. maybe you can enhance that?

ok ok got it :)
