### ISSUE TITLE
Calculator extension

### ISSUE THREAD

**Issue by MeetaHaldar** [ridsuteri/Awesome-Chrome-Extensions#21]
Hello @ridsuteri,
I want to add Calculator extension to this repository.
it will help the users to calculate their respective numbers and also their will be 'log' so that the user can also calculate log things.
if you assign me this issue i can do work on it.

Thanks and regards,
Meeta Haldar,
A GSSOC 2022 Contributor.

**Comment by kalashvasaniya** [comment]
Hey, Assigne this to me!

**Comment by ridsuteri** [comment]
@kalashvasaniya the issues will be assigned on fcfs basis, since @MeetaHaldar has opened the issue she will be assigned first, if she fails to submit a pr you will assigned with the issue :)

**Comment by ridsuteri** [comment]
@MeetaHaldar any updates on this?

**Comment by MeetaHaldar** [comment]
is there no PR from this?? 
i had made PR on this please check

**Comment by ridsuteri** [comment]
> is there no PR from this?? i had made PR on this please check

suggested you a change with the PR, pls rectify that
