### ISSUE TITLE
Add a TO-DO List Extension

### ISSUE THREAD

**Issue by Atharv-110** [ridsuteri/Awesome-Chrome-Extensions#22]
Hey @ridsuteri, imagine someone codes on leetcode for hours and how much easy would be for him to organize his whole day with an extension. So here I am with the TO-DO List extension and for sure it would help every coder to keep a distance from his/her phone to again and again look for the next task.

**Comment by kalashvasaniya** [comment]
Hey, Assigne this to me!

**Comment by ridsuteri** [comment]
looks great @Atharv-110, go ahead :)

**Comment by ridsuteri** [comment]
@kalashvasaniya issues are being assigned on first comes first served basis :)

**Comment by Atharv-110** [comment]
Hey @ridsuteri can you please label this in GSSoC'22

**Comment by ridsuteri** [comment]
closing this issue since the PR is merged
