### ISSUE TITLE
Title: Live chatting application 

### ISSUE THREAD

**Issue by kalashvasaniya** [ridsuteri/Awesome-Chrome-Extensions#225]
### Is your feature request related to a problem? Please describe.

You can chat directly through extension!

### Describe the solution you'd like.

Big project need time max 7 days

### Describe alternatives you've considered.

NA

**Comment by navyasharma0203** [comment]
I would like to work on this issue. Can you assign this to me?

**Comment by ridsuteri** [comment]
any updates @kalashvasaniya ?

**Comment by kalashvasaniya** [comment]
> any updates @kalashvasaniya ?

Sorry for the extream delay due to my exam I can't make any PRs!

**Comment by kalashvasaniya** [comment]
Ok so this issue take lot of my time so for now I close this issue
