### ISSUE TITLE
Redesign website

### ISSUE THREAD

**Issue by Adhetya** [ridsuteri/Awesome-Chrome-Extensions#228]
### What happened?

The website UI can be made better by choosing a better colour scheme as well as a better font. I will also try to fix as many broken image links as possible.

I am a GSSOC 22 contributor. Please assign. this issue to me.

### How can we reproduce this bug?

Visit the awesome-chrome-extensions website

**Comment by praniti111** [comment]
Go forward with it @Adhetya
