### ISSUE TITLE
Minor enhancements in documentation

### ISSUE THREAD

**Issue by abhilipsasahoo03** [ridsuteri/Awesome-Chrome-Extensions#23]
Hi @ridsuteri, I'm a GSSOC'22 contributor and I'd like to work on README.md file to fix broken image link, shield links and work on other minor enhancements.

**Comment by ridsuteri** [comment]
@abhilipsasahoo03 another same issue ( #19 ) is already open, Please wait for him to submit a PR that will fix broken links, you can work on further improvements after that :)

**Comment by abhilipsasahoo03** [comment]
> @abhilipsasahoo03 another same issue ( #19 ) is already open, Please wait for him to submit a PR that will fix broken links, you can work on further improvements after that :)

Thanks for letting me know!

**Comment by ridsuteri** [comment]
ok so @abhilipsasahoo03 I am assigning you the issue, go ahead :)

**Comment by abhilipsasahoo03** [comment]
> ok so @abhilipsasahoo03 I am assigning you the issue, go ahead :)

Yeah, the shield images and the extension image still look broken to me on GitHub Mobile App. I'll work on it.

**Comment by abhilipsasahoo03** [comment]
> > ok so @abhilipsasahoo03 I am assigning you the issue, go ahead :)
> 
> Yeah, the shield images and the extension image still look broken to me on GitHub Mobile App. I'll work on it. Thanks, again! :)
