### ISSUE TITLE
Code Compilation and Execution Extension 

### ISSUE THREAD

**Issue by shreya024** [ridsuteri/Awesome-Chrome-Extensions#233]
### Is your feature request related to a problem? Please describe.

This extension returns the compilation and execution results of the code evaluation request(code).

### Describe the solution you'd like.

I'll be implementing it using the Hackerearth API

### Describe alternatives you've considered.

I am a GSSOC Contributor.Kindly assign @ridsuteri

**Comment by ridsuteri** [comment]
any updates @shreya024 ?
