### ISSUE TITLE
Window Remover Extension

### ISSUE THREAD

**Issue by iamrahulmahato** [ridsuteri/Awesome-Chrome-Extensions#238]
### Is your feature request related to a problem? Please describe.

When we work in the browser, knowingly or unknowingly we make many windows of the browser but when it comes to controlling the windows or closing them we have to do it manually and don't have any solutions

### Describe the solution you'd like.

So we will create a Window Remover Extension

feature:
Remove recent window
Remove Other windows
Remove All windows

### Describe alternatives you've considered.
I am a GSSOC Contributor.

### Add any other context or screenshots about the feature request here.
ss:
![Screenshot 2022-05-06 154258](https://user-images.githubusercontent.com/49890655/167225645-42f0c98e-9900-43a8-ad23-d710a329483b.png)

**Comment by ridsuteri** [comment]
@iamrahulmahato isn't this issue similar to the control chrome tab extension ?(#209)

**Comment by iamrahulmahato** [comment]
@ridsuteri  Similar but it works on only tabs I am taking about the popup windows when make a lot pop up windows while working

**Comment by ridsuteri** [comment]
ok go ahead

**Comment by iamrahulmahato** [comment]
@ridsuteri the pr is made #251
