### ISSUE TITLE
Title: I will add a Leetcode Formatter to the awesome chrome extenstion list.

### ISSUE THREAD

**Issue by AmolShelke2** [ridsuteri/Awesome-Chrome-Extensions#239]
### Is your feature request related to a problem? Please describe.

No, my feature is not a request related to a problem.

### Describe the solution you'd like.

This Extension is very useful for the developers who solve leetcode coding challenges, without this extension they have to write code on vs code and then paste it to the leetcode code editor. instead of that, they can use this extension to write the code beautifully formatted.

### Describe alternatives you've considered.

no, I have not considered any alternative.

### Add any other context or screenshots about the feature request here.

![Leetcode format - Chrome Web Store - Google Chrome 08-05-2022 11 03 58 AM](https://user-images.githubusercontent.com/95171638/167283513-4fba4629-0a2f-4936-897f-4594de7cca1a.png)

@ridsuteri kindly review this issue.

**Comment by ridsuteri** [comment]
@AmolShelke2 This looks like an existing one. Did you make this one? Because right now we are just allowing custom-made extensions...

**Comment by AmolShelke2** [comment]
Ohh sorry I though you are accepting all extension you can close this issue.
