### ISSUE TITLE
Make a Dynamic Calendar Extension!

### ISSUE THREAD

**Issue by kalashvasaniya** [ridsuteri/Awesome-Chrome-Extensions#24]
Make an extension of calendar. Make use of creativity and add new features on your own to add their usability! Happv
contributing,

Hey I want to work on this issue!

**Comment by kalashvasaniya** [comment]
Hey I want to work on this issue!

**Comment by ridsuteri** [comment]
@kalashvasaniya looks great, go ahead :)

**Comment by tasneemahmed123** [comment]
Make an extension of calendar. Make use of creativity and add new features on your own to add their usability!

I want to work on this issue , assign it to me, please

**Comment by ridsuteri** [comment]
@tasneemahmed123 a PR is already open for this issue :((
