### ISSUE TITLE
Facts Extension

### ISSUE THREAD

**Issue by Sukriti-m** [ridsuteri/Awesome-Chrome-Extensions#257]
### Is your feature request related to a problem? Please describe.

Facts Extension

### Describe the solution you'd like.

I will make a Facts Extension in which the user will get to know about a fascinating fact and this will enhance the user's knowledge.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

I am contributor at GSSoC '22. Please assign this issue to me.
@praniti111 @ridsuteri

**Comment by Akshima-Ghai** [comment]
Issue assigned @Sukriti-m
