### ISSUE TITLE
Vocabulary Extension

### ISSUE THREAD

**Issue by Sukriti-m** [ridsuteri/Awesome-Chrome-Extensions#258]
### Is your feature request related to a problem? Please describe.

Vocabulary Extension

### Describe the solution you'd like.

I will make a Vocabulary Extension in which the user will get to learn new words along with their meanings.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

I am contributor at GSSoC '22. Please assign this issue to me.
@praniti111 @ridsuteri

**Comment by Akshima-Ghai** [comment]
Issue assigned @Sukriti-m. All the best
