### ISSUE TITLE
Flight Tracker Extension

### ISSUE THREAD

**Issue by shreya024** [ridsuteri/Awesome-Chrome-Extensions#263]
### Is your feature request related to a problem? Please describe.

This extension will showcase Real-time Flight Status.

### Describe the solution you'd like.

I will implement it using this api https://aviationstack.com/

### Describe alternatives you've considered.

I am a GSSOC contributor.Kindly assign @ridsuteri

**Comment by Akshima-Ghai** [comment]
issue assigned @shreya024

**Comment by ridsuteri** [comment]
any updates on this @shreya024 ?

**Comment by shreya024** [comment]
> any updates on this @shreya024 ?

Sorry my exams are going soon...will try my best to work on it soon

**Comment by shreya024** [comment]
@ridsuteri Done.Kindly review .I would also like to add a second PR by tomorrow night having more features and better UI.

**Comment by ridsuteri** [comment]
@shreya024 given some feedback on that PR
