### ISSUE TITLE
File counter Extension

### ISSUE THREAD

**Issue by iamrahulmahato** [ridsuteri/Awesome-Chrome-Extensions#266]
### Is your feature request related to a problem? Please describe.

In the web development process sometimes we need to count the how mush title or files linked to that website like CSS and js files

### Describe the solution you'd like.

For that we make an extension that will help you to count number of 
heading tags
CSS links
js links

### Describe alternatives you've considered.

I am a GSSOC Contributor.

### Add any other context or screenshots about the feature request here.

ss:
![ss1you](https://user-images.githubusercontent.com/49890655/167981695-8181c102-0633-4fc9-8d69-273724daeb72.png)

**Comment by Akshima-Ghai** [comment]
issue assigned @iamrahulmahato

**Comment by iamrahulmahato** [comment]
@Akshima-Ghai pr is made #281
