### ISSUE TITLE
Water Break Extension!

### ISSUE THREAD

**Issue by kalashvasaniya** [ridsuteri/Awesome-Chrome-Extensions#27]
This extension reminds you after each 30 minutes to take a break and drink water. As soon as the countdown ends the extension alerts you with an alarm sound.
Hey I Want to work on this issue!

**Comment by kalashvasaniya** [comment]
Hey I Want to work on this issue!

**Comment by ridsuteri** [comment]
@kalashvasaniya go ahead :)

**Comment by kalashvasaniya** [comment]
@ridsuteri I made this extension & you also merged to main so pls. remove this from the issue
