### ISSUE TITLE
BMI Calculator

### ISSUE THREAD

**Issue by Areebah03** [ridsuteri/Awesome-Chrome-Extensions#276]
### Is your feature request related to a problem? Please describe.

I want to add a project of BMI calculator.

### Describe the solution you'd like.

This will calculate your BMI and the range where you lie accordingly.

### Describe alternatives you've considered.

I am a GSSOC contributor. Kindly assign @ridsuteri

### Add any other context or screenshots about the feature request here.

![6](https://user-images.githubusercontent.com/85051124/168410430-142d5b7d-02f6-4208-a514-75d21791c662.png)

**Comment by Akshima-Ghai** [comment]
issue assigned @Areebah03

**Comment by ridsuteri** [comment]
sorry @Areebah03 but a bmi calculator already exists in the project, Hence we can't assign this duplicate issue to you again :(
