### ISSUE TITLE
Windows 11 animation

### ISSUE THREAD

**Issue by Areebah03** [ridsuteri/Awesome-Chrome-Extensions#277]
### Is your feature request related to a problem? Please describe.

It is animation effect of windows 11

### Describe the solution you'd like.

I will add animation effect of windows 11

### Describe alternatives you've considered.

I am GSSoC Contributor. Kindly assign @ridsuteri 

### Add any other context or screenshots about the feature request here.

https://user-images.githubusercontent.com/85051124/168410552-82ae4af8-634c-4b21-b0b3-b01892c7d4fa.mp4

**Comment by Akshima-Ghai** [comment]
issue assigned @Areebah03

**Comment by ridsuteri** [comment]
> ### Is your feature request related to a problem? Please describe.
> It is animation effect of windows 11
> 
> ### Describe the solution you'd like.
> I will add animation effect of windows 11
> 
> ### Describe alternatives you've considered.
> I am GSSoC Contributor. Kindly assign @ridsuteri
> 
> ### Add any other context or screenshots about the feature request here.
>  New.Tab.-.Google.Chrome.2022-05-12.16-53-55.mp4

this doesn't seem like a chrome extension...
is it?
also, this doesn't look much useful, 
sorry I have to close this one too :(
