### ISSUE TITLE
Form validation 

### ISSUE THREAD

**Issue by Areebah03** [ridsuteri/Awesome-Chrome-Extensions#279]
### Is your feature request related to a problem? Please describe.

I have made a form validation project that validate a form according to email, username and phone number and gives error if not written according to syntax.

### Describe the solution you'd like.

I would like to add it .

### Describe alternatives you've considered.

I am a GSSoC contributor please assign @ridsuteri 

### Add any other context or screenshots about the feature request here.

![ss9](https://user-images.githubusercontent.com/85051124/168412811-beb45b3a-a7e2-4bb9-8a50-2e04727d738b.png)

**Comment by ridsuteri** [comment]
@Areebah03 I don't think this extension will be of any use, Hence I am closing it :(
