### ISSUE TITLE
Link Shortener

### ISSUE THREAD

**Issue by kodepirate** [ridsuteri/Awesome-Chrome-Extensions#28]
Hlo @ridsuteri I would like  to add a **link shortener** in this project under GSSOC-2022.

**Comment by ridsuteri** [comment]
great, go ahead @kodepirate :)

**Comment by kodepirate** [comment]
This is issue no #28 You have already assigned it to me

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903 can you assign me? Please assign me and give some detailed information on what issue you are facing using this link shortener.

**Comment by ridsuteri** [comment]
@sceary-expert the issue is fixed by the PR #59
