### ISSUE TITLE
Fahrenheit_Celsius_Converter

### ISSUE THREAD

**Issue by Sukriti-m** [ridsuteri/Awesome-Chrome-Extensions#283]
### Is your feature request related to a problem? Please describe.

Fahrenheit_Celsius_Converter

### Describe the solution you'd like.

I will add the extension in which the user can enter the Fahrenheit value of temperature and on clicking the button, the user will receive Celsius value and vice-versa.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

I am contributor at GSSoC '22. Please assign this issue to me.
@praniti111 @ridsuteri @Akshima-Ghai

**Comment by navyasharma0203** [comment]
I would like to work on this issue. Can you assign this to me?

**Comment by Sukriti-m** [comment]
> I would like to work on this issue. Can you assign this to me?

Hii @navyasharma0203 
This issue is already assigned to me and I am working on it. If you want ,you can create a different issue and then the mentors will assign it to you.
