### ISSUE TITLE
add some cool fonts

### ISSUE THREAD

**Issue by Khushbu-kumari-87090** [ridsuteri/Awesome-Chrome-Extensions#29]
i really want to work on this project . so please assign me and guide me please.

**Comment by ridsuteri** [comment]
@Khushbu-kumari-87090 please elaborate on the issue, Like you want to add fonts for?

**Comment by adi7yashah** [comment]
I am a participant of GSSOC'22. I want to work on this issue .Can you please assign me?
I will definitely do this work properly.

**Comment by ridsuteri** [comment]
@adi7yashah issues will be assigned on fcfs basis :)

**Comment by tasneemahmed123** [comment]
Hello, I will be happy to work on this issue, I will add cool fonts like: times new roman , calibiri and some cool fonts , I am sure , that you will like that when i begin on this

**Comment by ridsuteri** [comment]
@Khushbu-kumari-87090 are you there or should I assign this to someone else?

**Comment by Khushbu-kumari-87090** [comment]
Actually i am  busy some other work so yeah you can assign to anyone.

**Comment by ridsuteri** [comment]
@adi7yashah are you interested in this?
if yes, then please specify the changes you will make

**Comment by SandeepShekhawat8778** [comment]
@ridsuteri assign me this issue );

**Comment by ridsuteri** [comment]
@Sanghu01 and @tasneemahmed123 are you interested in taking this issue?

**Comment by ridsuteri** [comment]
> @ridsuteri assign me this issue );

You will be assigned this issue if these two fails to work on this

**Comment by Sanghu01** [comment]
> 
yes

**Comment by SandeepShekhawat8778** [comment]
@ridsuteri but I think that please give them a deadline so if they both fail to work on this issue after you will assign this issue to me so that can I start working on this issue.

**Comment by ridsuteri** [comment]
> > 
> 
> yes

ok please specify the changes you will make?

**Comment by ridsuteri** [comment]
I am closing this issue since it has become obsolete!
