### ISSUE TITLE
Manually block website

### ISSUE THREAD

**Issue by DragonUncaged** [ridsuteri/Awesome-Chrome-Extensions#297]
### Is your feature request related to a problem? Please describe.

Add url to block website

### Describe the solution you'd like.

Will upload soon

### Describe alternatives you've considered.

.

**Comment by ridsuteri** [comment]
@DragonUncaged isn't it similar to #253 ?

**Comment by DragonUncaged** [comment]
> @DragonUncaged isn't it similar to #253 ?

That's mine only

**Comment by ridsuteri** [comment]
yeah please don't open duplicate issue :(

**Comment by DragonUncaged** [comment]
> yeah please don't open duplicate issue :(

Mistake
