### ISSUE TITLE
Enhance the README file

### ISSUE THREAD

**Issue by Susmita-Dey** [ridsuteri/Awesome-Chrome-Extensions#30]
**I am contributor at GSSoC'22. Please assign this issue to me.**

**Comment by ridsuteri** [comment]
@Susmita-Dey few issues ( #19  )are already open for the readme improvements :)
please wait for them to submit a pr, you can start working on the issue after that :)

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey few issues ( #19 )are already open for the readme improvements :) please wait for them to submit a pr, you can start working on the issue after that :)

Okay

**Comment by ridsuteri** [comment]
@Susmita-Dey you want to do any enhancements in the readme?

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey you want to do any enhancements in the readme?
Yes

**Comment by ridsuteri** [comment]
ok please suggest the changes you will make

**Comment by ridsuteri** [comment]
> > ok please suggest the changes you will make
> 
> I want to use some emojis and add a few lines to it

Well but Please make sure that you add something meaning full to it :))

**Comment by Susmita-Dey** [comment]
> Well but Please make sure that you add something meaning full to it :))
Yes, sure. Thanks for assigning this issue to me.

**Comment by ridsuteri** [comment]
updates @Susmita-Dey ?

**Comment by Susmita-Dey** [comment]
> updates @Susmita-Dey ?

Yes, creating the PR.
