### ISSUE TITLE
SEO for chrome extension

### ISSUE THREAD

**Issue by Khushbu-kumari-87090** [ridsuteri/Awesome-Chrome-Extensions#31]
please assign me for this project.

**Comment by Sukeerti1** [comment]
I am a GSSoC22 participant, and would like to work on this project and contribute to this repo!
Please assign me the project!

**Comment by ridsuteri** [comment]
@Khushbu-kumari-87090 any updates?

**Comment by ridsuteri** [comment]
@Sukeerti1 you want to work on this issue?
if yes then please specify the changes you will make
