### ISSUE TITLE
Title: BMI Calculator

### ISSUE THREAD

**Issue by Areebah03** [ridsuteri/Awesome-Chrome-Extensions#311]
### Is your feature request related to a problem? Please describe.

I want to add a BMI calculator with amazing design. This website will first take height and weight of user and calculate the BMI. Then it will show the range in which the user is laying i.e normal, underweight, overweight or obesity.

### Describe the solution you'd like.

It is  made using html, css, javascript.

### Describe alternatives you've considered.

I am contributor at GSSoC '22. Please assign this issue to me.
@praniti111 @ridsuteri @Akshima-Ghai

### Add any other context or screenshots about the feature request here.

![ss1](https://user-images.githubusercontent.com/85051124/168975244-094f8e7d-a5c3-4939-b5d2-452c65a87c87.png)
![ss2](https://user-images.githubusercontent.com/85051124/168975275-357b4c29-e271-4fb3-a068-1d634d291fff.png)

**Comment by praniti111** [comment]
@Areebah03 The extension of BMI calculation is already been made.
