### ISSUE TITLE
Sport News Chrome Extension

### ISSUE THREAD

**Issue by hariketsheth** [ridsuteri/Awesome-Chrome-Extensions#318]
### Is your feature request related to a problem? Please describe.

- Extension required for Sport News

### Describe the solution you'd like.

- A Chrome Extension required for Sport News (Latest)

### Describe alternatives you've considered.

.

**Comment by ridsuteri** [comment]
@hariketsheth an extension that gives news across all the domains is already there in the repo(including sports)...
so I don't think adding another similar one will be of any great use, hence I am closing this issue :(
