### ISSUE TITLE
docs: Adding a Pull Request Template

### ISSUE THREAD

**Issue by Pradumnasaraf** [ridsuteri/Awesome-Chrome-Extensions#32]
### Chnages 
- Adding a PR template
- Template path **`.github/PULL_REQUEST_TEMPLATE.md`**

### Template Preview (while creating a PR.)
![Screenshot from 2022-03-01 17-54-32](https://user-images.githubusercontent.com/51878265/156168840-66822d65-3e60-4026-8064-f967d66cf94b.png)

- Contribution towards GSsoc`22, Thank you

**Comment by ridsuteri** [comment]
It is much needed @Pradumnasaraf , go ahead :)
