### ISSUE TITLE
change Mouse Pointer

### ISSUE THREAD

**Issue by DragonUncaged** [ridsuteri/Awesome-Chrome-Extensions#322]
### Is your feature request related to a problem? Please describe.

The Mouse pointer will be of different icons then normal

### Describe the solution you'd like.

will upload soon

### Describe alternatives you've considered.

.

**Comment by ridsuteri** [comment]
@DragonUncaged can you please elaborate on the issue?

**Comment by DragonUncaged** [comment]
The Icon of the Mouse Will Change to the Different one

> @DragonUncaged can you please elaborate on the issue?

The Icon of the Mouse Will Change to the Different one
