### ISSUE TITLE
Redirect Link Checker

### ISSUE THREAD

**Issue by DragonUncaged** [ridsuteri/Awesome-Chrome-Extensions#324]
### Is your feature request related to a problem? Please describe.

Check the all the link of the website that is there.
Find he link that is not working.

### Describe the solution you'd like.

will upload soon

### Describe alternatives you've considered.

.

**Comment by ridsuteri** [comment]
@DragonUncaged can you club this with screen recorder extension?
as these are closely related and will be of greater use...

**Comment by DragonUncaged** [comment]
> @DragonUncaged can you club this with screen recorder extension? as these are closely related and will be of greater use...

this is very specialize for the screenshot.
it cannot happen

**Comment by ridsuteri** [comment]
Please make the PR before 10-11PM today, if you want this contribution to be  counted in GSSoC'22
