### ISSUE TITLE
Title: Tic-Tac-Toe

### ISSUE THREAD

**Issue by Areebah03** [ridsuteri/Awesome-Chrome-Extensions#327]
### Is your feature request related to a problem? Please describe.

I want to add an amazing game of tic-tac-toe of 2 players played on same computer screen with awesome design and animation. It also has music feature in it.

### Describe the solution you'd like.

It is made using html, css, javascript.

### Describe alternatives you've considered.

I am contributor at GSSoC '22. Please assign this issue to me.
@praniti111 @ridsuteri @Akshima-Ghai

### Add any other context or screenshots about the feature request here.

![ss1](https://user-images.githubusercontent.com/85051124/169464273-03bab58a-cb2d-4519-b276-0317ec8984d9.png)
![ss5](https://user-images.githubusercontent.com/85051124/169464333-313b8e99-2a27-4802-97e7-a0af7442f826.png)

**Comment by ridsuteri** [comment]
Tic tac toe extension has already been added :(
