### ISSUE TITLE
Creating issue Forms for the repo

### ISSUE THREAD

**Issue by MonarchGitHub** [ridsuteri/Awesome-Chrome-Extensions#33]
I want to add a few issue Forms so that it will be convenient for new contributors to open issues. I plan to create  **Bug Report** and **Feature Request** Forms. You can read more about issue forms [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

**_The Bug Report issue form will have the following fields_**

- **Description of the bug**
- **How to Reproduce**
- **Expected behavior**
- **Urgency indicator**
- **Desktop Info (OS, Version, Browser etc):**

**_The Feature Request issue form will have the following fields_**

- **Is your feature request related to a problem? Please describe.**
- **Describe the solution you'd like**
- **Describe alternatives you've considered**

**Timeline- I can complete this task by 3 March**

**Comment by ridsuteri** [comment]
Much needed @MonarchGitHub , go ahead :)

**Comment by MonarchGitHub** [comment]
Thanks, im on it.

**Comment by SonikeshKumar14** [comment]
Hi! I would like to work on this issue under GSSOC`22. Please assign it to me.

**Comment by ridsuteri** [comment]
> Hi! I would like to work on this issue under GSSOC`22. Please assign it to me.

closed already :(
