### ISSUE TITLE
DIY ideas extension

### ISSUE THREAD

**Issue by Sukriti-m** [ridsuteri/Awesome-Chrome-Extensions#372]
### Is your feature request related to a problem? Please describe.

DIY ideas extension

### Describe the solution you'd like.

I will make an extension in which the user will get various DIY ideas.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

I am contributor at GSSoC '22. Please assign this issue to me.
@praniti111 @ridsuteri @Akshima-Ghai

**Comment by Akshima-Ghai** [comment]
issue assigned @Sukriti-m
