### ISSUE TITLE
Title: step-progress-bar

### ISSUE THREAD

**Issue by kalashvasaniya** [ridsuteri/Awesome-Chrome-Extensions#373]
### Is your feature request related to a problem? Please describe.

Hey I made step-progress-bar Project Which Is Very Good!

### Describe the solution you'd like.

This Project is very Helpfull,
I Make This Project With the help of HTML, CSS & JavaScript.

### Describe alternatives you've considered.

The CSS & JavaScript Code are Available in very well mannered! & Easy to understand!

**Comment by kalashvasaniya** [comment]
@praniti111 Pls. assign this to me

**Comment by ridsuteri** [comment]
@kalashvasaniya Progress bar for what?
can you explain

**Comment by kalashvasaniya** [comment]
> @kalashvasaniya Progress bar for what?
> can you explain

like this ->
<img width="504" alt="Screenshot 2022-05-25 at 10 24 32 AM" src="https://user-images.githubusercontent.com/88212870/170182709-ec498488-d92f-43a1-a8e0-cd4383f7acae.png">

**Comment by ridsuteri** [comment]
> > @kalashvasaniya Progress bar for what?
> > can you explain
> 
> like this -> <img alt="Screenshot 2022-05-25 at 10 24 32 AM" width="504" src="https://user-images.githubusercontent.com/88212870/170182709-ec498488-d92f-43a1-a8e0-cd4383f7acae.png">

that looks nice but how will this be useful?

**Comment by kalashvasaniya** [comment]
> > > @kalashvasaniya Progress bar for what?
> > > can you explain
> > 
> > 
> > like this -> <img alt="Screenshot 2022-05-25 at 10 24 32 AM" width="504" src="https://user-images.githubusercontent.com/88212870/170182709-ec498488-d92f-43a1-a8e0-cd4383f7acae.png">
> 
> that looks nice but how will this be useful?

Just count the step if you are doing some work!

**Comment by ridsuteri** [comment]
ok cool go ahead
