### ISSUE TITLE
Shark Tank memes Extension

### ISSUE THREAD

**Issue by VagishaGupta9** [ridsuteri/Awesome-Chrome-Extensions#38]
This extension will generate shark tank memes and it will be a fun ad blocker.
I would like to take up this task and i'm a gssoc'22 participant.

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903 can you assign me? Please assign me and give some detailed information on what issue you are facing using shark tank memes.

**Comment by ridsuteri** [comment]
@VagishaGupta9 any updates on this?

**Comment by ridsuteri** [comment]
@sceary-expert you want to work on this?
