### ISSUE TITLE
Want to improve footer section of the website

### ISSUE THREAD

**Issue by ruchichaurasia24** [ridsuteri/Awesome-Chrome-Extensions#391]
Need to have some content and social icons on the footer section. Can I work on this issue.

Footer section looks like:-
<img width="943" alt="Untitledchrome" src="https://user-images.githubusercontent.com/77578662/170528289-ca819571-34f5-4431-a2ea-3faa9e628a2e.png">

**Comment by ridsuteri** [comment]
@ruchichaurasia24 go-ahead
also since the responsiveness of the site needs to be fixed , you can open another issue for that as well

**Comment by ridsuteri** [comment]
Please make the PR before 10-11PM today, if you want this contribution to be  counted in GSSoC'22

**Comment by Roshani9731** [comment]
@ridsuteri Can I work on this issue?

**Comment by ridsuteri** [comment]
> @ridsuteri Can I work on this issue?

yes go ahead :)
