### ISSUE TITLE
Title: animated-search-bar

### ISSUE THREAD

**Issue by kalashvasaniya** [ridsuteri/Awesome-Chrome-Extensions#397]
### Is your feature request related to a problem? Please describe.

Hey I made animated-search-bar Project Which Is Very Good!

### Describe the solution you'd like.

This Project is very Helpfull,
I Make This Project With the help of HTML, CSS & JavaScript.

### Describe alternatives you've considered.

The CSS & JavaScript Code are Available in very well mannered! & Easy to understand!

**Comment by ridsuteri** [comment]
@kalashvasaniya animated search for?
can you elaborate this...

**Comment by kalashvasaniya** [comment]
> @kalashvasaniya animated search for?
> can you elaborate this...

Just an animation that's it assign this pls. & Give lvl 1

**Comment by ridsuteri** [comment]
> > @kalashvasaniya animated search for?
> > can you elaborate this...
> 
> Just an animation that's it assign this pls. & Give lvl 1

umm I don't think this can be of any much use, sorry can't assign this :(
