### ISSUE TITLE
Mouse pointer Icon

### ISSUE THREAD

**Issue by DragonUncaged** [ridsuteri/Awesome-Chrome-Extensions#403]
### Is your feature request related to a problem? Please describe.

Change the Mouse pointer Icon.

### Describe the solution you'd like.

.

### Describe alternatives you've considered.

.

**Comment by ridsuteri** [comment]
@DragonUncaged I Have already closed this issue already once (#322 ), I am requesting again and again that please don't spam.
I know that the program is ending and you are excited to score but this is not the correct way...
