### ISSUE TITLE
Title: Age Calculatpr

### ISSUE THREAD

**Issue by Areebah03** [ridsuteri/Awesome-Chrome-Extensions#406]
### Is your feature request related to a problem? Please describe.

I want to add a project on age calculator that takes birthday of user as input and gives respective age of the person.

### Describe the solution you'd like.

Build using HTML, CSS, JavaScript.

### Describe alternatives you've considered.

I am contributor at GSSoC '22. Please assign this issue to me.
@praniti111 @ridsuteri @Akshima-Ghai

### Add any other context or screenshots about the feature request here.

![ss1](https://user-images.githubusercontent.com/85051124/170722047-4493bc76-ee6d-41f0-93d4-82a129920f0d.png)

**Comment by ridsuteri** [comment]
@Areebah03 the extension is already present, can't assign the duplicate one :(
