### ISSUE TITLE
Music Downloader

### ISSUE THREAD

**Issue by DragonUncaged** [ridsuteri/Awesome-Chrome-Extensions#412]
### Is your feature request related to a problem? Please describe.

An Extension Used to Download music from the website like jiosavan

### Describe the solution you'd like.

.

### Describe alternatives you've considered.

.

**Comment by ridsuteri** [comment]
@DragonUncaged is it allowed? legally?

**Comment by DragonUncaged** [comment]
> @DragonUncaged is it allowed? legally?

No
