### ISSUE TITLE
Mobile Code Extension

### ISSUE THREAD

**Issue by Sukriti-m** [ridsuteri/Awesome-Chrome-Extensions#420]
### Is your feature request related to a problem? Please describe.

Mobile Code Extension

### Describe the solution you'd like.

I will make a mobile code extension in which the user will type the name of a country and on clicking the button will get the mobile code of that country.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

I am contributor at GSSoC '22. Please assign this issue to me.
@praniti111 @ridsuteri @Akshima-Ghai

**Comment by ridsuteri** [comment]
@Sukriti-m I think you have added a similar extension with the country code name?

**Comment by Sukriti-m** [comment]
> @Sukriti-m I think you have added a similar extension with the country code name?

That contained short country code. For example, France can be written as FRA. India as IND.
But this will contain the phone number code of different countries such as for India we write +91.

**Comment by ridsuteri** [comment]
oh ohk sorry my bad, go ahead :)
