### ISSUE TITLE
Search Country By Capital Extension

### ISSUE THREAD

**Issue by Sukriti-m** [ridsuteri/Awesome-Chrome-Extensions#421]
### Is your feature request related to a problem? Please describe.

Search Country By Capital Extension

### Describe the solution you'd like.

I will make a search Country By Capital extension in which the user will type the name of a capital city and on clicking the button will get the name of that country.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

 I am contributor at GSSoC '22. Please assign this issue to me.
@praniti111 @ridsuteri @Akshima-Ghai

**Comment by ridsuteri** [comment]
Please make the PR before 10-11PM today, if you want this contribution to be  counted in GSSoC'22
