### ISSUE TITLE
Want to improve CSS part of homepage 

### ISSUE THREAD

**Issue by vedsom** [ridsuteri/Awesome-Chrome-Extensions#428]
### Is your feature request related to a problem? Please describe.

when we open the website it's not much user friendly with black back ground and other issues related to css and html part. 

### Describe the solution you'd like.

I will add proper css styles and some html code to make this site more user friendly.

### Describe alternatives you've considered.

There is no such alternatives but i am sure above solution will get work done.

**Comment by vedsom** [comment]
@ridsuteri  mam i will surely complete it within 1-2 hr so please assign me the task.

**Comment by ridsuteri** [comment]
go ahead @vedsom :)

**Comment by vedsom** [comment]
@ridsuteri sir thankyou for assigning.
