### ISSUE TITLE
Timer Extension

### ISSUE THREAD

**Issue by Me-keer** [ridsuteri/Awesome-Chrome-Extensions#43]
Hi, @ridsuteri I am a contributor @ GSSOC'22, and I wud like to add a timer extension to your project.

**Comment by Sanghu01** [comment]
I want to work on this issue under gssoc'22

**Comment by ridsuteri** [comment]
ok @Me-keer go ahead :)

**Comment by ridsuteri** [comment]
@Sanghu01 issues will be assigned on fcfs basis, if @Me-keer fails to submit a PR, you will be assigned with this issue :)

**Comment by ridsuteri** [comment]
@Me-keer any updates on this issue?

**Comment by ridsuteri** [comment]
@Me-keer you want to work on this?

**Comment by Me-keer** [comment]
I will not be able to complete in the given deadline sir.

**Comment by ridsuteri** [comment]
@Me-keer do you want to take some more time then?

**Comment by VartikaB** [comment]
I want to work on this issue. Can I work on this issue?
