### ISSUE TITLE
Country Area Extension

### ISSUE THREAD

**Issue by Sukriti-m** [ridsuteri/Awesome-Chrome-Extensions#430]
### Is your feature request related to a problem? Please describe.

Country Area Extension

### Describe the solution you'd like.

I will make an extension in which the user will type the name of a country and on clicking the button will get the area of that country.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

I am contributor at GSSoC '22. Please assign this issue to me.
@praniti111 @ridsuteri @Akshima-Ghai

**Comment by ridsuteri** [comment]
@Sukriti-m area of that country means?

**Comment by Sukriti-m** [comment]
> @Sukriti-m area of that country means?

means area per metre square which a oarticular country occupies

**Comment by Sukriti-m** [comment]
> > Please make the PR before 10-11PM today, if you want this contribution to be counted in GSSoC'22
> 
> alright

Please assign this issue to me as the Gssoc period will end tomorrow now.
