### ISSUE TITLE
Github Theme

### ISSUE THREAD

**Issue by DragonUncaged** [ridsuteri/Awesome-Chrome-Extensions#439]
### Is your feature request related to a problem? Please describe.

GitHub Theme it changes the Background of the Github.com website

### Describe the solution you'd like.

.

### Describe alternatives you've considered.

.

**Comment by ridsuteri** [comment]
what does this issue do? please elaborate?

**Comment by ridsuteri** [comment]
> /assign

please don't do such things @DragonUncaged , I have said this earlier as well. Don't just try to get the scores by putting spammy issues :(
