### ISSUE TITLE
Quote Generator extension

### ISSUE THREAD

**Issue by vaibhavmehro** [ridsuteri/Awesome-Chrome-Extensions#45]
some kind of quote generator and to give the thought for the day on each day login

**Comment by shreelakshmijoshi** [comment]
Hey @vaibhavmehro, I would like to work on this issue.

**Comment by vaibhavmehro** [comment]
ok go for it and do give leads.

**Comment by vaibhavmehro** [comment]
ok thanks @ridsuteri .
