### ISSUE TITLE
Images are missing on the home page of some chrome extensions. Kindly assign this issue to me 

### ISSUE THREAD

**Issue by mayank2002-jpg** [ridsuteri/Awesome-Chrome-Extensions#454]
### What happened?

When you open the home page, some of the extensions don't show the image, only the alt tag.
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/74871225/183235142-472ad1f7-b04f-4841-a9b9-2fd8805a0393.PNG">

### How can we reproduce this bug?

Just add the correct URL of images in the tag.

### Urgency (Optional)

High priority

**Comment by ridsuteri** [comment]
@mayank2002-jpg Please wait for the contribution period to start, will start assigning you the issues after that

**Comment by ridsuteri** [comment]
@mayank2002-jpg you can start working on it

**Comment by mayank2002-jpg** [comment]
Thanks for assigning me this issue

**Comment by mayank2002-jpg** [comment]
I have completed this and got merged into the main code. So kindly remove this issue.
