### ISSUE TITLE
Title: Number System Converter 

### ISSUE THREAD

**Issue by niteshjangid29** [ridsuteri/Awesome-Chrome-Extensions#455]
### Is your feature request related to a problem? Please describe.

Hello Sir/Ma'am,
I would like to firstly work on **Proper Designing** the **Binary to Decimal Convertor**,  with proper Border, width, color, borderRadius, etc. Width changes every time when we calculate a new conversion.

As soon as you provide me the issue, I can get to work.
Waiting for your response

### Describe the solution you'd like.

Firstly I will **design** it with a **good UI** using proper HTML, and CSS. Then, I will add new features

### Describe alternatives you've considered.

I will add new features to it Like **Binary to Hexadecimal**, **Decimal to Hexadecimal**, **Binary to Hexadecimal**, etc., with a proper design.

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/99542740/183291531-5f42634b-62f8-4877-8bb4-982f27778cc5.png)

**Comment by Sukriti-m** [comment]
@niteshjangid29 you can start working on this issue.

**Comment by niteshjangid29** [comment]
Okay

**Comment by niteshjangid29** [comment]
I have completed the issue and it got merged as well.
Should I now close this issue as **close as completed.**
