### ISSUE TITLE
Title: Improve the UI of the website. 

### ISSUE THREAD

**Issue by SujalSamai** [ridsuteri/Awesome-Chrome-Extensions#456]
### Is your feature request related to a problem? Please describe.

The UI of the website doesn't looks very pleasing right now. 
The header section and the cards can be made much better.

### Describe the solution you'd like.

I would like to improve the UI of the header section with better fonts and alignment, and also making the cards look much better by adding rounded corners.

### Describe alternatives you've considered.

Header section can be improved with better choice of Font, and alignment can be made better using something like flexbox.

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/87236576/183296602-09cecec9-8ee7-4fd1-80a4-d5ca652f710c.png)

**Comment by narayan954** [comment]
marking as completed
