### ISSUE TITLE
Title: Password Generator

### ISSUE THREAD

**Issue by dishant-yadav** [ridsuteri/Awesome-Chrome-Extensions#457]
### Is your feature request related to a problem? Please describe.

Hello Sir,

I would like to work on the **Password Generator** which facilitates users with a tool to generate passwords. I will be creating a good **UI** using proper **HTML**, and **CSS**.

As soon as you provide me the issue, I can get to work.
Waiting for your response

### Describe the solution you'd like.

The solution is quite simple.
- I will first design a nice looking UI with HTML and CSS. Using the JS will have the functionality to generate the passwords.
- I will be having four variables, for storing the **uppercase**, **lowercase**, **digits** and **special characters**.
- Then using the **random** function in JS will pick up **four characters** from **all the four variables** and **concat** them into a variable.

### Describe alternatives you've considered.

I will be adding features like
-  **controlling the password length.**
- **selecting the type of characters(choosing only uppercase or choosing only numbers).**

**Comment by dishant-yadav** [comment]
@ridsuteri can you please assign me this issue?

**Comment by its-harsshhh** [comment]
@dishant-yadav hope you working on this issue.

**Comment by dishant-yadav** [comment]
Yeah I am working on it!!!
