### ISSUE TITLE
Title: Adding a Favicon to webpage 

### ISSUE THREAD

**Issue by anshulsoni4** [ridsuteri/Awesome-Chrome-Extensions#458]
### Is your feature request related to a problem? Please describe.

there was no favicon so, thought of adding it.

### Describe the solution you'd like.

will add a favicon that will be displayed in the browser tab

### Describe alternatives you've considered.

we can make custom favicon for this webpagea

**Comment by Sukriti-m** [comment]
Hello @anshulsoni4
This is a very minor issue. Please create an issue that can be valuable to this project.

**Comment by anshulsoni4** [comment]
Alright @Sukriti-m :)
