### ISSUE TITLE
docs: Add documentation Issue templates

### ISSUE THREAD

**Issue by Pradumnasaraf** [ridsuteri/Awesome-Chrome-Extensions#46]
### Chnages 
- Adding Issue templates
- Template path **`.github/ISSUE_TEMPLATE`**

###Template Types
![Screenshot from 2022-03-01 21-03-49](https://user-images.githubusercontent.com/51878265/156198784-b2e8d551-3df4-4aff-a7c7-051a88c344c0.png)

### Template Preview (while creating an issue - bug.)
![Screenshot from 2022-03-01 18-03-48](https://user-images.githubusercontent.com/51878265/156169861-53b91128-a1aa-4751-805e-affb8a4924a3.png)

####  Due to that we are also missing out on some checks on the community standards checklist

![Screenshot from 2022-03-02 09-46-06](https://user-images.githubusercontent.com/51878265/156294010-0eea1326-b530-4502-bec1-64414e985ab3.png)

**Comment by ridsuteri** [comment]
> ### Chnages
> * Adding Issue templates
> * Template path **`.github/ISSUE_TEMPLATE`**
> 
> ###Template Types ![Screenshot from 2022-03-01 21-03-49](https://user-images.githubusercontent.com/51878265/156198784-b2e8d551-3df4-4aff-a7c7-051a88c344c0.png)
> 
> ### Template Preview (while creating an issue - bug.)
> ![Screenshot from 2022-03-01 18-03-48](https://user-images.githubusercontent.com/51878265/156169861-53b91128-a1aa-4751-805e-affb8a4924a3.png)
> 
> #### Due to that we are also missing out on some checks on the community standards checklist
> ![Screenshot from 2022-03-02 09-46-06](https://user-images.githubusercontent.com/51878265/156294010-0eea1326-b530-4502-bec1-64414e985ab3.png)
> 
> #### Contribution towards GSsoc`22, Thank you

Haven't you added the issue template and PR template earlier?
How is this issue different from the earlier ones?

**Comment by ridsuteri** [comment]
> Yes yes, this issue template, the previous one was the PR template. **The template will come when opening an issue like this [one](https://github.com/Pradumnasaraf/Pradumnasaraf/issues/new/choose).**

Check PR #40 which fixes #33

**Comment by ridsuteri** [comment]
Is your issue different from the already merged one?
if yes then please specify

**Comment by Pradumnasaraf** [comment]
> Is your issue different from the already merged one? if yes then please specify

Yes, there is one template missing we can add that, documentation one.

**Comment by ridsuteri** [comment]
ok go ahead then :)

**Comment by tasneemahmed123** [comment]
I love to work on this issue, assign this issue to me

**Comment by Pradumnasaraf** [comment]
> I love to work on this issue, assign this issue to me

PR is already opened, please try finding some other issues
