### ISSUE TITLE
Title: Frontend design for Fahrenheit to Celsius Converter [SSOC]

### ISSUE THREAD

**Issue by dhruvbhatia1** [ridsuteri/Awesome-Chrome-Extensions#460]
### Is your feature request related to a problem? Please describe.

The extension doesn't look very visually appealing.

### Describe the solution you'd like.

Would like to change the frontend of the extension to make it look more visually appealing and professional.
Would like to change the color scheme using CSS, use better fonts, and improve the button styling used.

### Describe alternatives you've considered.

Can also add Bootstrap to make the extension look better.

**Comment by dhruvbhatia1** [comment]
@ridsuteri can this issue be assigned to me?

**Comment by narayan954** [comment]
Yes @dhruvbhatia1 you can work on this :)
