### ISSUE TITLE
Title: Joke Maker extension 

### ISSUE THREAD

**Issue by anshulsoni4** [ridsuteri/Awesome-Chrome-Extensions#463]
### Is your feature request related to a problem? Please describe.

I would like to make a Chrome extension that can tell us jokes when we want to. 

### Describe the solution you'd like.

when you enable or click on that extension a dialog box popup will appear which will tell you a joke.

### Describe alternatives you've considered.

I will add new features to it like a button that will generate jokes with sound effects.

**Comment by Sukriti-m** [comment]
Hello @anshulsoni4 
This extension already exists in this project.

**Comment by anshulsoni4** [comment]
Uhh 
Alright, can I edit the ui of some extension?

**Comment by Sukriti-m** [comment]
> Uhh Alright, can I edit the ui of some extension?

Yes, you can.

**Comment by anshulsoni4** [comment]
so i have customized the BMI Extention pls check my PR @Sukriti-m
