### ISSUE TITLE
Title: Editing some components and css of BMI extension

### ISSUE THREAD

**Issue by anshulsoni4** [ridsuteri/Awesome-Chrome-Extensions#465]
### Is your feature request related to a problem? Please describe.

the form of this extension is not centered, and the buttons, heading is not aligned properly.and 

### Describe the solution you'd like.

center the heading and texts, with a hover effect on the buttons, with increase the border radius for the form

### Describe alternatives you've considered.

can change the color of the whole extension page, with some shadow effects on the box of form and other animations to the inputs.

**Comment by SMD-1** [comment]
yes @anshulsoni4  you can work on this

**Comment by anshulsoni4** [comment]
thanks @SMD-1

**Comment by anshulsoni4** [comment]
merged !
