### ISSUE TITLE
Title : Want to add Currency Convertor project [SSOC]

### ISSUE THREAD

**Issue by ravish036** [ridsuteri/Awesome-Chrome-Extensions#467]
### Description 

- This Web extension help you to convert any currency amount to a selected currency within seconds.
- Help you to easy to calculate rates in different currencies which saves your efforts and time while comparing diff stocks and NFT's rates.
- Tech-Stack used -> HTML5, CSS, JAVASCRIPT, API's.

### Screenshots 
Before conversion :- ![image](https://user-images.githubusercontent.com/84343005/184208788-1a0cb091-fb41-4326-8a83-7d207021315b.png)

After conversion :- 
![image](https://user-images.githubusercontent.com/84343005/184208650-7cd3aaf5-db80-43b8-a426-57f59a8be594.png)

**Comment by its-harsshhh** [comment]
@ravish036 a similar extension already exists in the repository, so I can't assign the exactly duplicate issue to you again :(( but do let me know if you want to modify the existing one...
