### ISSUE TITLE
Pomodoro Extension

### ISSUE THREAD

**Issue by Arindam-Mondal** [ridsuteri/Awesome-Chrome-Extensions#469]
### Pomodoro Chrome Extension

This extension will help someone to manage their task efficiently.
Many a times we get deviated and loose our focus.
So, using the Pomodoro technique we can set the timer and start focusing on the task - then take a short break and again focus on  the task.
So, using this extension user can set a timer and once the time is over user would be getting a alarm notification.

### How Pomodoro technique works

**The original technique has six steps:**

- Decide on the task to be done.
- Set the pomodoro timer (typically for 25 minutes).
- Work on the task.
- End work when the timer rings and take a short break (typically 5–10 minutes).
- If you have finished fewer than three pomodoros, go back to Step 2 and repeat until you go through all three pomodoros.
- After three pomodoros are done, take the fourth pomodoro and then take a long break (typically 20 to 30 minutes). 
- Once the long break is finished, return to step 2.

### Describe the solution you'd like.

Build a chrome extension 
- To set the timer to focus on a particular task.
- To set the timer for short break
- To set timer for long break

### Describe alternatives you've considered.

Alternative can be to build a simple **notification** extension -  where we can set the time for which someone wants to focus on any task.

### Add any other context or screenshots about the feature request here.

<img width="266" alt="image" src="https://user-images.githubusercontent.com/9895635/184474731-8ced4f9e-094b-4025-99c0-cb22e6ffc221.png">

**Comment by its-harsshhh** [comment]
@Arindam-Mondal this extension is already added in repository.
