### ISSUE TITLE
Wordle Game Extension

### ISSUE THREAD

**Issue by gaurikapoplai21** [ridsuteri/Awesome-Chrome-Extensions#47]
Want to build a chrome extension for the game Wordle. UI will be similar to the one on the New York Times site. To generate a word and validate the  test words's existence in the dictionary, I'll be using some external API. Pls assign this issue to me. @ridsuteri 

-GsSOC participant

**Comment by SonikeshKumar14** [comment]
Hi! I would like to work on this issue under GSSOC`22. Please assign it to me.

**Comment by ridsuteri** [comment]
sounds great @gaurikapoplai21, you can start working on the issue :)

**Comment by ridsuteri** [comment]
@SonikeshKumar14 Please wait for @gaurikapoplai21 to submit a PR, if she fails to submit one, I will assign this issue to you :)

**Comment by ridsuteri** [comment]
any update on this @gaurikapoplai21 ?

**Comment by gaurikapoplai21** [comment]
Yeah it's almost done. I'll submit a PR tomorrow

**Comment by gaurikapoplai21** [comment]
Soory , didnt get time yesterday. I'm gonna submit the PR today in a couple of hours :)

**Comment by ridsuteri** [comment]
any updates @gaurikapoplai21 ?
