### ISSUE TITLE
Dice-Roller

### ISSUE THREAD

**Issue by Sanskar50** [ridsuteri/Awesome-Chrome-Extensions#470]
![Screenshot (72)](https://user-images.githubusercontent.com/99363431/184494257-0dbdbada-67dd-4cd2-ac0f-79ac324f1a83.png)
![Screenshot (73)](https://user-images.githubusercontent.com/99363431/184494265-11fb5844-0cb2-49c4-b020-858ae86f2d62.png)

## DICE ROLLER
# Features

- Generates random number on the dice on clicking the "Roll" button.
- Has two different switchable themes " light "and "dark" for eye comfort.

# Tech Stack

- Html , CSS ,Bootstrap , Javascript

**Comment by its-harsshhh** [comment]
Ummm @Sanskar50 That doesn't seem to be of much use, maybe try coming up with something useful or make this one something more useful :(

**Comment by Sanskar50** [comment]
@its-harsshhh Can please suggest what feature can I add to make this more useful or any other simple project idea .This is my first contribution need some suggestions from you.
