### ISSUE TITLE
Title: UI enhancements 

### ISSUE THREAD

**Issue by VasuDevrani** [ridsuteri/Awesome-Chrome-Extensions#473]
### Some of the problems are:
- navbar and page aren't completely responsive
- the dark mode feature has multiple issues as well like it fails to change colors at some place
- No favicon for the website
- search option problems
- the project cards doesn't have any substitute image if the image is not provided
- lacks some worthy animations
- lacks other UI enhancements

Please assign it to me.
Thanks

### Describe the solution you'd like.

I can enhance the UI of the website and make it look awesome. I would like to make this contribution.
This can be done in two ways:
- first I can upgrade the code to ReactJS with Tailwind powerboost. 
- second, I can make the changes in existing html, css, js code

### Describe alternatives you've considered.

Already described above

### Add any other context or screenshots about the feature request here.

Website is itself a visual, no screenshots needed

**Comment by its-harsshhh** [comment]
@VasuDevrani you can start working on it :)

**Comment by VasuDevrani** [comment]
Thank You so much, but you didn't choose the option..
- first I can upgrade the code to ReactJS with Tailwind powerboost.
- second, I can make the changes in existing html, css, js code

**Comment by its-harsshhh** [comment]
@VasuDevrani go with second one

**Comment by VasuDevrani** [comment]
Hey @its-harsshhh 
I'm actually done with the home page of website, I just want to show some glimpse of the work and wanna know if you are satisfied with the color scheme

- dark mode, ui improvement, cool animations and full responsiveness ensured
- image bug is yet to be solved, working on it and other HELP, ABOUT pages

![image](https://user-images.githubusercontent.com/101383635/184669995-bc50a804-5ac2-4048-ac00-074dd101e822.png)
![image](https://user-images.githubusercontent.com/101383635/184670348-6160e9be-daa8-4032-8f64-cc490db98a5d.png)

**Comment by its-harsshhh** [comment]
@VasuDevrani it's look awesome buddy...keep going !

**Comment by VasuDevrani** [comment]
Hey @its-harsshhh 
I'm facing one problem....
For the changes, i made a new branch "UI_ENHANCED", and i just want to push those changes for merge
My forked origin says its 2 commit behind the upstream...What's this? should i just ignore this and push the changes

**Comment by VasuDevrani** [comment]
Hey @its-harsshhh all done now...
You can check it out....also i have done huge amount of changes, so please check it out, everything alright by the way

**Comment by narayan954** [comment]
Great work Vasu, marking this as solved now!
