### ISSUE TITLE
Title: Digital Clock || enhancement

### ISSUE THREAD

**Issue by hacker626** [ridsuteri/Awesome-Chrome-Extensions#478]
# SSOC 2022
### Is your feature request related to a problem? Please describe.

For the given [chrome extensions](https://github.com/ridsuteri/Awesome-Chrome-Extensions/tree/main/digital_clock),I want to add feature to modify the time format with single button from 12-Hr format to 24-Hr and vice-versa..

### Describe the solution you'd like.

- To modify the UI to look better
- To enhance feature to switch between 12-Hr to 24-Hr format and vice versa

### Describe alternatives you've considered.

To Introduce a CSS button just below the time display which will switch the time-format.

**Comment by priyanshi1282** [comment]
@hacker626 you can start working on it :)

**Comment by priyanshi1282** [comment]
@hacker626 hope you are working on it :)

**Comment by hacker626** [comment]
I have already requested for pull request which is already being merged: 
https://github.com/ridsuteri/Awesome-Chrome-Extensions/pull/479
Please check it.

**Comment by priyanshi1282** [comment]
great work @hacker626 , Thanks for contributing :)
