### ISSUE TITLE
Title: Dark Mode disappears on a refresh

### ISSUE THREAD

**Issue by narayan954** [ridsuteri/Awesome-Chrome-Extensions#480]
### What happened?

After toggling the dark mode , when I got to refresh the page, dark mode disappeared. This was not expected to happen.

### How can we reproduce this bug?

just toggle the dark mode and refresh the web page, Dark mode is gone!

### Urgency (Optional)

Medium priority

**Comment by narayan954** [comment]
Anyone willing to take this task can work on this. But get yourself assigned first.
Hint- Browser Cookies might help

**Comment by SujalSamai** [comment]
> Anyone willing to take this task can work on this. But get yourself assigned first. Hint- Browser Cookies might help

Hey!! I would love to do this task, can you assign it to me?

**Comment by narayan954** [comment]
sure go on!!

**Comment by deeproop** [comment]
@narayan954  Please review, this issue is solved by #484

**Comment by narayan954** [comment]
@deeproop  Thanks a lot for the reminder Deep... @SujalSamai  Sorry Sujal, but this issue was taken on by #482 before you could and is resolved. I have to close the issue as resolved.
