### ISSUE TITLE
Problems with website

### ISSUE THREAD

**Issue by VasuDevrani** [ridsuteri/Awesome-Chrome-Extensions#482]
### What happened?

There are few errors yet to be solved, reference to #477

- Some new extension folders are named with space like 'FOLDER NAME', this space causes error while browser tries to access image location. The spaces in name must be removed and also a contributing guideline stating this issue should be added.

- Dark mode changes on refresh

- The names of files: about.html and help.html need to be amended in href links
CHANGE
Help.html -> help.html
About.html -> about.html

- Some more bugs need to be resolved.

You may assign this to me. I would be happy to help

### How can we reproduce this bug?

Already elaborated.

**Comment by deeproop** [comment]
You cannot change the folder name as permission is not granted by the maintainers to do the same :(

**Comment by VasuDevrani** [comment]
@its-harsshhh

**Comment by narayan954** [comment]
@deeproop  but ig you can create a pr for the same

**Comment by narayan954** [comment]
@VasuDevrani Sounds great, you can help with this issue :)

**Comment by narayan954** [comment]
@VasuDevrani Hey can you please confirm if all the naming issue as you mentioned was resolved in #481 already ? and if so, some images still have little typos in their URL , can you update issue accordingly. Thank you!

**Comment by deeproop** [comment]
@narayan954 Hi, I have mentioned what changes needed to be done while committing the PR please have a look #481 PR. :)

**Comment by deeproop** [comment]
> @deeproop but ig you can create a pr for the same

No we cannot, I have tried it but it's restricted.

**Comment by narayan954** [comment]
@deeproop yes , I had a look Deep . Thanks for your contributions :)

**Comment by deeproop** [comment]
Glad to contribute :))

**Comment by VasuDevrani** [comment]
@narayan954 there are still some issues with the website
- dark mode changes on refresh
- files aren't linked as they should be, so whenever i tries to move between pages in the website, it crashes with 404
- some other bugs...

I'll remove all by the end of today
