### ISSUE TITLE
Title: URL Task organiser

### ISSUE THREAD

**Issue by tejasrialluru** [ridsuteri/Awesome-Chrome-Extensions#485]
### Is your feature request related to a problem? Please describe.

This extension is a combination of both bookmarks and a to-do list, with enhanced features.

A lot of times it happens that we are doing a particular task on a webpage, like, reading an article, collecting information for a project, filling out a form, ordering an item on an e-commerce website, etc, and we have to leave that task unfinished due to some other important work. If we again want to get back to that task, we have to bookmark that page, save the URL of the page manually or leave that particular tab opened.

The problem with the above ways are:
1. Bookmark tab visibility is limited, so, generally we use it to save the links that we will be frequently visiting in the future.
2. Manually saving the URL somewhere is very cumbersome.
3. Having so many tabs opened will slow down the browser and becomes difficult to find one particular tab from so many.

### Describe the solution you'd like.

- Automatically save the URL of the webpage the user is using with just one click.
- User can add a remark describing the task while saving.
- Tasks can be organizes into folders.
- Every time the user opens a new tab, a list of folders and corresponding tasks are shown which are clickable.
- Also, a motivational quote is shown every time the new tab is opened along with the task list.
- the user can delete the task and also folders once the tasks are completed.

### Describe alternatives you've considered.

- Every time the user visits any webpage in the pending tasks, an alert is displayed reminding about the task.

### Add any other context or screenshots about the feature request here.

![WhatsApp Image 2022-09-01 at 7 14 16 PM](https://user-images.githubusercontent.com/78372756/187929624-259b343e-4fe0-4f24-b46f-094110ab837a.jpeg)

**Comment by its-harsshhh** [comment]
sorry @tejasrialluru , the similar extension is already added in the repository
