### ISSUE TITLE
Title: Enhancement to Height-Conversion-tool

### ISSUE THREAD

**Issue by tejasrialluru** [ridsuteri/Awesome-Chrome-Extensions#486]
### Height-Conversion-tool

Currently, this extension only provides an option to convert from feet to cm.

### Describe the solution you'd like.

1. Add a feature to convert from cm to feet.
2. Improve the existing UI.

### Describe alternatives you've considered.

No response

### Alternative approach

No response

### Add any other context or screenshots about the feature request here.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/78372756/187980450-b7cf82ad-5c8d-489b-a61c-f9625ff3748d.png">

**Comment by narayan954** [comment]
Thanks for creating the issue @tejasrialluru , you can start working on it :) , but please follow the issue template from the next time and contribution guidelines as well. 
Regards.

**Comment by its-harsshhh** [comment]
@narayan954 before assigning issues, you must check is the similar extension already available or not ?
kindly check this https://github.com/ridsuteri/Awesome-Chrome-Extensions/issues/153

**Comment by narayan954** [comment]
@its-harsshhh it's an enhancement not a new extension.

**Comment by newbie2508** [comment]
Is this issue still open?
I would like to work on it, if no is working on it

**Comment by narayan954** [comment]
@tejasrialluru  could you tell us if you're working on this issue?

**Comment by newbie2508** [comment]
Can i create a pull request, I am done with the code @its-harsshhh
