### ISSUE TITLE
Title: Typing Speed Calculator

### ISSUE THREAD

**Issue by Joiyad** [ridsuteri/Awesome-Chrome-Extensions#488]
### Is your feature request related to a problem? Please describe.

It is frustrating to visit different websites to measure typing speed.  A chrome extension for the measurement of typing speed will make it convenient to measure typing speed and accuracy.

### Describe the solution you'd like.

This extension will allow users to measure their typing speed and accuracy. It will make it handy to check typing speed anytime. It is easy to use and will provide a wonderful experience with a beautiful UI.

### Describe alternatives you've considered.

This extension will fetch different quotes each time which makes it engaging and will display the accuracy and speed of typing.

### Add any other context or screenshots about the feature request here.

![Screenshot (13)](https://user-images.githubusercontent.com/90030250/189715000-0adc61c4-331c-4695-b886-a1b32a59c635.png)

**Comment by Joiyad** [comment]
Kindly assign me this issue.

**Comment by narayan954** [comment]
Sorry @Joiyad  but #298 also does the similar thing.

**Comment by Joiyad** [comment]
@narayan954  I have seen that extension #298 which is a game for user engagement, it doesn't tell a user about typing speed and accuracy but shows a score which is calculated on the basis of the typed word, it doesn't take into account the accuracy and speed and focus only on completion of the word.

**Comment by narayan954** [comment]
Ok you can work on this or just as a suggestion, would you like to enhance that game and provide these functionalities as well?

**Comment by Joiyad** [comment]
According to me, the purpose both extensions serve is different and that's why I would like to make it a new extension. Further, I will try to complete it as soon as possible.

**Comment by narayan954** [comment]
yes you're right, go ahead !

**Comment by Joiyad** [comment]
Could you assign it an SSoC label
