### ISSUE TITLE
Age calculator

### ISSUE THREAD

**Issue by d3mEnt0r** [ridsuteri/Awesome-Chrome-Extensions#490]
If I write an age that is in the future like 01 Jan 2030 than it still gives back a reply 8 years 8 months 12 days. I can add a feature like according to the age group we can display personalized entertaining messages to the user.
please review this and assign this issue to me.

![Screenshot (48)](https://user-images.githubusercontent.com/97298773/189972654-55d28e11-3bf7-4d2b-b263-cf2ebd85af68.png)

**Comment by its-harsshhh** [comment]
@d3mEnt0r , similar extension is already added in the repo https://github.com/ridsuteri/Awesome-Chrome-Extensions/issues/406
