### ISSUE TITLE
Title: Changing the UI of Roots_Quadratic_Eqn

### ISSUE THREAD

**Issue by newbie2508** [ridsuteri/Awesome-Chrome-Extensions#492]
### Is your feature request related to a problem? Please describe.

The present UI of this extension is simple and does not have a good user experience.

It looks like this at present
<img width="960" alt="image" src="https://user-images.githubusercontent.com/97738900/191546464-bbb59dce-a519-4377-b48f-400cc6d5c0f6.png">

### Describe the solution you'd like.

I want the user to understand the formula, so the formula should be there
I want the UI to be better, so that user wants to use it

### Describe alternatives you've considered.

 I want to add descriptive text for each text box and formula for better user experience

**Comment by narayan954** [comment]
Great, you can work on this ! : )

**Comment by newbie2508** [comment]
Thank you :)

**Comment by narayan954** [comment]
closed this as solved
