### ISSUE TITLE
Title: Changing the UI of Translator extension

### ISSUE THREAD

**Issue by Drishti-jain21** [ridsuteri/Awesome-Chrome-Extensions#493]
### Is your feature request related to a problem? Please describe.

The current UI of the translator chrome extension is really plain. It does not have any colors

It looks like this
<img width="960" alt="image" src="https://user-images.githubusercontent.com/100796147/191551706-89caae0e-1aed-4507-8372-7b3445445b56.png">

### Describe the solution you'd like.

I want the extension to have a better user experience

### Describe alternatives you've considered.

I want to add more colors, change the positioning and add better effects

**Comment by narayan954** [comment]
you can work on this issue and please provide screenshots of the change :)

**Comment by Drishti-jain21** [comment]
Thank you
I will

**Comment by narayan954** [comment]
closing this as completed
