### ISSUE TITLE
Calculate Age Project not showing preview image

### ISSUE THREAD

**Issue by rtewari056** [ridsuteri/Awesome-Chrome-Extensions#495]
### What happened?

**Describe the bug**
Calculate Age Project not showing preview image on projects homepage

**Expected behavior**
Should show the preview image for website visitors.

**Screenshots**

![calculate age project bug](https://user-images.githubusercontent.com/75976169/192077546-e5332edf-3f34-4fab-b04f-c1f40f670686.png)

### How can we reproduce this bug?

1. Go to 'Awesome Chrome Extensions' homepage
2. Search for 'Calculate Age' project
3. See the bug

### Desktop Information (Optional)

OS: Windows 11
Browser: Chrome
Version: 105.0.5195.127

**Comment by narayan954** [comment]
its a really minor fix and caused by #487 , would look into that
