### ISSUE TITLE
Title: Random Choice Maker

### ISSUE THREAD

**Issue by dishant-yadav** [ridsuteri/Awesome-Chrome-Extensions#496]
### Is your feature request related to a problem? Please describe.

It often happens when we need to make choices so we either roll a dice or toss a coin. Its fine if we have 6 choices but what should we do when we have more than 6 choices. And even  one needs to label the numbers as choice 1, 2 and so on which leads to confusion. So I want to create choice picker extension.

### Describe the solution you'd like.

I would like to create a random choice picker where user would be able to add the choices and then the extension will randomly pick up a choice and display it.

### Describe alternatives you've considered.

Features like display options and change in the way of adding the choices.

**Comment by narayan954** [comment]
You can work on this @dishant-yadav and please provide screenshots of the features along with the pull request :)
