### ISSUE TITLE
TIC-TAC-TOE Chrome Extension

### ISSUE THREAD

**Issue by saujanyaraj07** [ridsuteri/Awesome-Chrome-Extensions#50]
Tic-Tac-Toe is one of the most popular games that we all have played.This extension lets you play tic-tac-toe in your browser

**Comment by ridsuteri** [comment]
sounds good @saujanyaraj07, go ahead :)

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903 can you assign me?
