### ISSUE TITLE
Profile Launcher Extension

### ISSUE THREAD

**Issue by Asmit2952** [ridsuteri/Awesome-Chrome-Extensions#52]
This extension will contain all of your social media links, which can be customized by users

Assign me this issue as I am a contributor in GSSoC'22

**Comment by ridsuteri** [comment]
@Asmit2952 This extension already exists by the name of link launcher :(

**Comment by ridsuteri** [comment]
If you want to  improve it you can open another issue for that :)

**Comment by Asmit2952** [comment]
> If you want to improve it you can open another issue for that :)

Sure!
