### ISSUE TITLE
Customized bookmark that has links to coding platforms like LeetCode, Codeforces, GFG, Codechef. Like an easy launcher for productivity

### ISSUE THREAD

**Issue by Varshini-k-02** [ridsuteri/Awesome-Chrome-Extensions#53]
@ridsuteri Can you assign this to me under GSSoC?

**Comment by ridsuteri** [comment]
sounds cool, go ahead @Varshini-k-02 :)

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903 can you assign me?

**Comment by ridsuteri** [comment]
@sceary-expert PR is merged, try looking out for some other issues :((
