### ISSUE TITLE
Title: Authentication to BMI Calculator extension. 

### ISSUE THREAD

**Issue by RavishaNewase** [ridsuteri/Awesome-Chrome-Extensions#54]
### Is your feature request related to a problem? Please describe.

In BMI Calculator extension, I would love to make some changes as it lags authentication.
If we even enter string instead of number it don't give any alert as well as it displays NaN if we enter anything except numbers in the input field. I will fix these issue by adding some authentication.

### Describe the solution you'd like.

I can authenticate the input fields based on condition. Along with these I will create error element which will be display if we give some wrong input for a particular time only.

### Describe alternatives you've considered.

Creating separate component for showing alert msg. eg. If by mistake user entered string instead of number in the input field alert msg will be displayed like please enter valid input etc. by creating new element.

### Add any other context or screenshots about the feature request here.

--GSSoC'22

**Comment by RavishaNewase** [comment]
---GSSoC'22

**Comment by ridsuteri** [comment]
sounds fun, go on @RavishaNewase :)

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903 can you assign me?

**Comment by ridsuteri** [comment]
any updates on this @RavishaNewase ?

**Comment by RavishaNewase** [comment]
> any updates on this @RavishaNewase ?

Hey!!
Actually I am quite busy these days due to college and other activities, But I will complete it by the end of these week.
Hope you are ok with this....

**Comment by ridsuteri** [comment]
> > any updates on this @RavishaNewase ?
> 
> Hey!! Actually I am quite busy these days due to college and other activities, But I will complete it by the end of these week. Hope you are ok with this....

Sure take your time :))

**Comment by RavishaNewase** [comment]
> > > any updates on this @RavishaNewase ?
> > 
> > 
> > Hey!! Actually I am quite busy these days due to college and other activities, But I will complete it by the end of these week. Hope you are ok with this....
> 
> Sure take your time :))

Hey!! I have sent you PR please check. I have completed task from my side. If there are any issues pls let me know.

**Comment by RavishaNewase** [comment]
> > > > any updates on this @RavishaNewase ?
> > > 
> > > 
> > > Hey!! Actually I am quite busy these days due to college and other activities, But I will complete it by the end of these week. Hope you are ok with this....
> > 
> > 
> > Sure take your time :))
> 
> Hey!! I have sent you PR please check. I have completed task from my side. If there are any issues pls let me know.

Pls check PR one more time, I have made necessary changes.

**Comment by ridsuteri** [comment]
> > > > > any updates on this @RavishaNewase ?
> > > > 
> > > > 
> > > > Hey!! Actually I am quite busy these days due to college and other activities, But I will complete it by the end of these week. Hope you are ok with this....
> > > 
> > > 
> > > Sure take your time :))
> > 
> > 
> > Hey!! I have sent you PR please check. I have completed task from my side. If there are any issues pls let me know.
> 
> Pls check PR one more time, I have made necessary changes.

still not working :((

**Comment by ridsuteri** [comment]
updates @RavishaNewase ?
