### ISSUE TITLE
Title: Revision Helper Extension

### ISSUE THREAD

**Issue by Shweta597** [ridsuteri/Awesome-Chrome-Extensions#55]
It is a Chrome Extension which is going to help in revising concepts by sending mail on the mentioned date with url and topic attach.

Basically this application has two parts:

1.Chrome Extension:-There is a form where you can add url, topic and date when you want to revise the topic.

2.Email Sender:- It is a Python Script which is going to check the database in every 24 hours and whenever any mentioned date is matched with today's date, it will send mail with topic and url attach.

**Comment by Shweta597** [comment]
Hi, @ridsuteri  I am a contributor @ GSSOC'22, and I would like to add a Revision Helper Extension to your project.

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903 can you assign me?

**Comment by ridsuteri** [comment]
any updates on this @Shweta597 ?

**Comment by ridsuteri** [comment]
do you want to work on this @sceary-expert ?
