### ISSUE TITLE
Title: Quotes Generator!

### ISSUE THREAD

**Issue by kalashvasaniya** [ridsuteri/Awesome-Chrome-Extensions#56]
### Is your feature request related to a problem? Please describe.

This extension generate new Quotes using APIs.

### Describe the solution you'd like.

Reading Quotes is very useful in daily life! 

### Describe alternatives you've considered.

This extension generate new quotes every time we click the new quote button.

**Comment by kalashvasaniya** [comment]
I really want to work on this issue!

**Comment by ridsuteri** [comment]
@kalashvasaniya similar issue #45 #11 are already open, Please don't open duplicate issues :(

**Comment by kalashvasaniya** [comment]
Ok sorry for that!
