### ISSUE TITLE
Want to add Ad blocker extension

### ISSUE THREAD

**Issue by anveshajain19** [ridsuteri/Awesome-Chrome-Extensions#7]
Hello @ridsuteri,
 I want to add an ad blocker extension to this repository.

Thanks and regards,
Anvesha Jain,
A GSSOC Contributor.

**Comment by ridsuteri** [comment]
@anveshajain19 go ahead , I am assigning you the issue :)

**Comment by anveshajain19** [comment]
Okay, Thankyou.
I will start my work from today itself :)

**Comment by Khushbu-kumari-87090** [comment]
hello ,i am so much interested  in your project, and i have  familiar with Html,css and java script so so can you please assign to  me this project.

**Comment by ridsuteri** [comment]
@Khushbu-kumari-87090 issues are assigned on first comes first served basis :)

**Comment by HarshKumarChoudary** [comment]
Hi there,
I'm a GSSOC22 contributor and I would like to contribute to this issue.
If the issue is still not completed then please assign it to me.

**Comment by ridsuteri** [comment]
@anveshajain19 since your latest PR is closed, do you want to give it another try or should I assign it to someone else?

**Comment by ridsuteri** [comment]
@Khushbu-kumari-87090 or @HarshKumarChoudary are you interested in taking this issue? If yes then please keep in mind not to submit a PR copied from [here](https://github.com/harshita214/Chrome-Extension/tree/main/AD%20BLOCKER)

**Comment by HarshKumarChoudary** [comment]
I could work on it. Please assign it to me.

**Comment by ridsuteri** [comment]
ok @HarshKumarChoudary go ahead, I am assigning you the issue now

**Comment by ridsuteri** [comment]
any updates @HarshKumarChoudary ?

**Comment by HarshKumarChoudary** [comment]
I got busy with exams. Will do it within two days

**Comment by Sulagna-Dutta-Roy** [comment]
Can I work on this Issue ?? please assign me then.

**Comment by ridsuteri** [comment]
ok go on @Sulagna-Dutta-Roy, I am assigning this to you
