### ISSUE TITLE
Pomodoro timer extension

### ISSUE THREAD

**Issue by michaelehab** [ridsuteri/Awesome-Chrome-Extensions#70]
The Pomodoro Technique is a time management method developed by Francesco Cirillo in the late 1980s. 
It uses a timer to break work into intervals, typically 25 minutes in length, separated by short breaks.
I'd like to make a chrome extension that manages time using the Pomodoro technique.
I'd like to work on this issue under GSSOC'22, kindly assign it to me.

**Comment by ridsuteri** [comment]
looks good, @michaelehab you can start working on it :))

**Comment by ridsuteri** [comment]
closing this since PR is merged :))
