### ISSUE TITLE
Title: Links and Tabs saver extension

### ISSUE THREAD

**Issue by gana-18** [ridsuteri/Awesome-Chrome-Extensions#71]
### Is your feature request related to a problem? Please describe.

Hello @ridsuteri,
I want to add a Links and Tabs saver extension to this repository.
Thanks and regards,
Gana Sai Teja,
A GSSOC Contributor :).

### Describe the solution you'd like.

This extension will help you to save links and tabs. This project is done in HTML, CSS, JavaScript

### Describe alternatives you've considered.

-GSSOC'22 :)

**Comment by ridsuteri** [comment]
sounds good, go ahead @gana-18, I am assigning you the issue :))
