### ISSUE TITLE
Change UI and add Download Button in QR Generator extension 

### ISSUE THREAD

**Issue by SainathPoojary** [ridsuteri/Awesome-Chrome-Extensions#74]
### I want to **change the UI** of QR Generator from:

<img src="https://user-images.githubusercontent.com/53347682/156917267-f111f922-d794-4e8d-bf46-ffb66c8cdc04.png" width="500" >

### To This:

<img src="https://user-images.githubusercontent.com/53347682/156917324-7eb252e0-bbbb-4340-83ab-60405b47f6ce.png" width="500" />

**Comment by ridsuteri** [comment]
looks cool @SainathPoojary, go-ahead

**Comment by SainathPoojary** [comment]
Hi @ridsuteri 👋, I have raised a Pull request, Please review it.
