### ISSUE TITLE
Title: Social media blocker / word of the day

### ISSUE THREAD

**Issue by Nehalmiglani** [ridsuteri/Awesome-Chrome-Extensions#75]
### Is your feature request related to a problem? Please describe.

I would like to create a social media  blocker extension 

### Describe the solution you'd like.

This extension will block the social media sites which will help students concentrate on studies more.

### Describe alternatives you've considered.

another alternative is the word of the day extension

**Comment by ridsuteri** [comment]
go ahead @Nehalmiglani

**Comment by ridsuteri** [comment]
any updates on this @Nehalmiglani?
