### ISSUE TITLE
Add a scientific calculator

### ISSUE THREAD

**Issue by Girlwithasmile** [ridsuteri/Awesome-Chrome-Extensions#76]
Hello, I am a gssoc'22 contributer and would like to add an extension of scientific calculator to your project. Pls asign this to me.

**Comment by ridsuteri** [comment]
@Girlwithasmile another calculator extension #21  is already open, I think it would be better if you could add these additional features to it.
What do you say?

**Comment by ridsuteri** [comment]
ok @Girlwithasmile you can start working on this issue :)
