### ISSUE TITLE
Add Paint cum quicknotes extension

### ISSUE THREAD

**Issue by Girlwithasmile** [ridsuteri/Awesome-Chrome-Extensions#77]
Hello, I am a gssoc'22 contributer and would like to add a paint(drawing tools) cum quicknotes extension in your project.

**Comment by ridsuteri** [comment]
sounds fun, go ahead :))

**Comment by ridsuteri** [comment]
any updates @Girlwithasmile ?

**Comment by Girlwithasmile** [comment]
Almost done shall make the pr tomorrow
