### ISSUE TITLE
Title: Auto refresher of the any page 

### ISSUE THREAD

**Issue by vaibhavmehro** [ridsuteri/Awesome-Chrome-Extensions#83]
### Is your feature request related to a problem? Please describe.

Yes. The user will not have to reload the page manually it will be done automatically.

### Describe the solution you'd like.

I would like to develop the auto refresher extension in which one can set the timer after which he/she would like to reload the page.
The extension will also give pop up when found a particular text on the page, which is under the targeted text.

### Describe alternatives you've considered.

I am a contributor under GSSOC so would like to work on this project.

**Comment by kunarkrawat** [comment]
Hey I would like to work on this issue.

**Comment by praniti111** [comment]
Reading your comment I see that your extension would do two tasks, auto-refresh and find a text from the web page right?

**Comment by vaibhavmehro** [comment]
Yes. Presentally i will be  working to the first part and would be adding the text finding thing in it.

**Comment by praniti111** [comment]
@kunarkrawat you can open a new issue with a different feature:)

**Comment by vaibhavmehro** [comment]
> @ridsuteri kindly assign the issue to me.

**Comment by vaibhavmehro** [comment]
@praniti111 @ridsuteri the task has been done kindly check for it. 
It works properly by setting the time for it.

**Comment by ridsuteri** [comment]
@vaibhavmehro please raise a PR

**Comment by vaibhavmehro** [comment]
@ridsuteri i have created it do check

**Comment by ridsuteri** [comment]
> @ridsuteri i have created it do check

sorry, can't find it :((
please do tag me in there

**Comment by vaibhavmehro** [comment]
@ridsuteri did you get it? actually there was some problem uploading that.

**Comment by ridsuteri** [comment]
yup merged by praniti, Thanks for contributing.
Closing the issue since PR is already merged :)

**Comment by vaibhavmehro** [comment]
it would be great if some more people will work on it to add some more features to it .
