### ISSUE TITLE
Change Background Color Extension

### ISSUE THREAD

**Issue by prathimacode-hub** [ridsuteri/Awesome-Chrome-Extensions#87]
### Is your feature request related to a problem? Please describe.

I would like to add a Background Color Changing Extension

### Describe the solution you'd like.

The purpose of this extension is to change the background color of the page. This is done using HTML, CSS and JS.

- [x] GSSoC  Contributor

Kindly assign it to me. @ridsuteri 

### Describe alternatives you've considered.

I'm a GSSoC contributor and would like to take up this issue.

### Add any other context or screenshots about the feature request here.

None

**Comment by ridsuteri** [comment]
any updates on this @prathimacode-hub ?

**Comment by prathimacode-hub** [comment]
Yes, PR will be done by tomorrow. @ridsuteri
