### ISSUE TITLE
Meaning of word extensions

### ISSUE THREAD

**Issue by abhi1e9-1e10** [ridsuteri/Awesome-Chrome-Extensions#9]
This Chrome extension allows you to instantly define a selected a word or phrase, using the  Dictionary, available via your membership. Once installed, users can select a word or phrase, right click on the highlighted word(s) and click Define Selection.

**Comment by saketsagarsingh** [comment]
When you will be labalize these issues i wanted to be assigned

**Comment by ridsuteri** [comment]
@saketsagarsingh will be adding labels in 1-2 days don't worry about that

**Comment by abhi1e9-1e10** [comment]
My college is going to offline, I have to go for exam preparations  so that I could not be able to contribute .
So please assign it to someone else.
