### ISSUE TITLE
Title: Random Joke Generator

### ISSUE THREAD

**Issue by kalashvasaniya** [ridsuteri/Awesome-Chrome-Extensions#91]
### Is your feature request related to a problem? Please describe.

Making Random Joke Generator Using API

### Describe the solution you'd like.

Use API to generator joke!

### Describe alternatives you've considered.

Made with use of HTML, CSS, JS.

**Comment by ridsuteri** [comment]
@kalashvasaniya a Random joke generator already exists in the repo, If you want, you can work on its improvement rather than adding a new one
